### ISSUE TITLE
nanmean() fails with array of dtype object (that contains numbers)

### ISSUE THREAD

**Issue by lebigot** [numpy/numpy#10393]
The following is a surprising exception:
```python
>>> np.nanmean(np.array([1, 2, 3], dtype=object))
Traceback (most recent call last):
…
  File "…/numpy/lib/nanfunctions.py", line 864, in nanmean
    avg = _divide_by_count(tot, cnt, out=out)
  File "…/numpy/lib/nanfunctions.py", line 183, in _divide_by_count
    return a.dtype.type(a / b)
AttributeError: 'int' object has no attribute 'dtype'
```
In fact, the expected result should unambiguously be 2.

This has a strong impact on arrays of objects, where objects can for instance be a mix of real numbers and [numbers with uncertainties](http://pythonhosted.org/uncertainties/): a mean that should work doesn't, which is particularly problematic, as means are a common operation.

NumPy version 1.14.0.

**Comment by rouckas** [comment]
Seems like a similar issue has already been solved in numpy mean and median by @charris (issue #4063).

**Comment by hylkedonker** [comment]
I can confirm that this bug still exists in Numpy version 1.19.1.

**Comment by lina-boljka** [comment]
still present in version 1.19.2

**Comment by cwe5590** [comment]
still present in version 1.20.1

**Comment by mattip** [comment]
No longer reproduces
```
>>> print(np.__version__)
2.6.0.dev0+git20260816.c452636
>>> np.nanmean(np.array([1, 2, 3], dtype=object))
np.float64(2.0)
```
