### ISSUE TITLE
allow utf-8 in the header string for savetxt

### ISSUE THREAD

**Issue by RizzerOnGitHub** [numpy/numpy#11040]
Bugs have been filed already on the lack of utf-8 support in savetxt, in #4543, #4939 and pull request #8644.

But those bugs address utf-8 data in the numpy array itself that is being saved.

A separate issue is support for utf-8 text in the header string. If I understand the operation of savetxt adequately, that should be relatively simple to fix. The header string can be handled differently to the bytedata in the array.

While the broader strategy for handling utf-8 in the array data is still being discussed in #8644, can the handling of the header string be fixed immediately?

**Comment by juliantaylor** [comment]
is this not also fixed in numpy 1.14 already?

**Comment by RizzerOnGitHub** [comment]
Thanks Julian, that will be great if it's already fixed.  I'm on Debian Linux with numpy 1.13.3, and 1.14 is not yet available for Debian.  I had assumed the bug still wasn't fixed since #4543, #4939 and #8644 were still active.  I'll report back to confirm once I've got numpy 1.14 installed.

**Comment by RizzerOnGitHub** [comment]
Confirmed. 

Nonascii (utf-8) text is still not working (in the header for savetxt) in numpy 1.13.3,
but is working in numpy 1.14.3.

Thanks for fixing the bug.
