### ISSUE TITLE
In histogram, bars whose count is larger than 2**31 sometimes become negative

### ISSUE THREAD

**Issue by chuangy1** [numpy/numpy#12029]
### Reproducing code example:

```python
import numpy as np

l = [(359, 218641918), (360, 346814771), (361, 221783064), (362, 228103721), (363, 226773168), (364, 340432095),
     (365, 892706639), (366, 350615631), (367, 402126509), (368, 315962305), (369, 397399137), (370, 419634877)
     ]
l1, l2 = zip(*l)
l1 = [i + 0.1 for i in l1]
min_l1, max_l1 = min(l1) // 5 * 5, max(l1) // 5 * 5 + 5
bins = int((max_l1 - min_l1) / 5 + 0.1)
hist, edges = np.histogram(l1, weights=l2, range=(min_l1, max_l1), bins=bins)
print(hist, edges)
```
### The actual output:
```python
[  218641918  1363906819 -2147483648   419634877] [355. 360. 365. 370. 375.]
```
The hist value can't be negative. It might be interger overflow.

### Numpy/Python version information:
1.14.5 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)]

**Comment by eric-wieser** [comment]
I'm pretty sure this is fixed in 1.15.0

**Comment by chuangy1** [comment]
> I'm pretty sure this is fixed in 1.15.0

I test in 1.15.2 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)], but the bug still exists.

**Comment by eric-wieser** [comment]
This is because your weights do not have a numpy dtype attached, and so default to `np.int_`. Using `weights=np.array(l2, np.int64)` or perhaps `weights=np.array(np.float64)` ought to fix the issue.

**Comment by InessaPawson** [comment]
Fixed in NumPy 2.0, where the default integer became 64-bit on 64-bit Windows, so list-based integer weights no longer default to int32.
The remaining behavior is documented in https://numpy.org/doc/stable/reference/generated/numpy.histogram.html. 
I think we can close this.
