### ISSUE TITLE
Attribute Error after installing v1.16.0 because pip is not uninstalling

### ISSUE THREAD

**Issue by treyenelson** [numpy/numpy#12736]
I pip installed the latest numpy and get the below error. The error goes away if I roll back to v1.15.4.
The most closely related issue I could find is #12028.

### Reproducing code example:

```python
import numpy as np
```

### Error message:

```
    Traceback (most recent call last):
      File "/home/trey/script.py", line 6, in <module>
        import numpy as np
      File "/home/trey/.local/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
        from . import core
      File "/home/trey/.local/lib/python3.6/site-packages/numpy/core/__init__.py", line 59, in <module>
        from . import numeric
      File "/home/trey/.local/lib/python3.6/site-packages/numpy/core/numeric.py", line 3093, in <module>
        from . import fromnumeric
      File "/home/trey/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 17, in <module>
        from . import _methods
      File "/home/trey/.local/lib/python3.6/site-packages/numpy/core/_methods.py", line 158, in <module>
        _NDARRAY_ARRAY_FUNCTION = mu.ndarray.__array_function__
    AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'
```

### Numpy/Python version information:
1.16.0
3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]

**Comment by charris** [comment]
Looks like you have a mix of two versions. Is this installed from source or wheels? Anyway, you might try deleting the current NumPy installs in your local directory before installing 1.16.

**Comment by oxygenxo** [comment]
I'm faced the same issue.
We're using Ubuntu 16.04 based Docker containers in our CI and using Tensorflow from pre-built wheel file which contains requirement 'numpy>=1.13.3'. I've got numpy version updated automatically from PyPI to 1.16.0 version today and my tests have failed with the following error on numpy import:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/__init__.py", line 59, in <module>
    from . import numeric
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/numeric.py", line 3093, in <module>
    from . import fromnumeric
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py", line 17, in <module>
    from . import _methods
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/_methods.py", line 158, in <module>
    _NDARRAY_ARRAY_FUNCTION = mu.ndarray.__array_function__
AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'
```
I've started to look at this and tried previous tag of the image. It contains numpy version 1.15.4. I've tried to upgrade numpy manually and it was ok:
```
$ sudo -E pip3 install --upgrade numpy
Installing collected packages: numpy
Successfully installed numpy-1.16.0
$ python3 
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> 
```

So I've decided to try to reinstall numpy manually inside container from "corrupted" image:
```
sudo pip3 uninstall numpy
```
But when I've tried to install it again I've got the following:
```
Requirement already satisfied: numpy in /usr/local/lib/python3.5/dist-packages
```
I've checked `/usr/local/lib/python3.5/dist-packages/numpy` directory and found that some files were here:
```
$ ls /usr/local/lib/python3.5/dist-packages/numpy
__pycache__  _import_tools.py  add_newdocs.py  core  distutils  testing
```
I've removed numpy directories and tried to install it again, and it worked.
So it seems that upgrade from 1.15.4 went fine, but from 1.13.1 (which was installed in "corrupted" image prior I've tried to upgrade numpy) something went wrong. May be I should upgrade pip?
```
$  pip3 --version
pip 9.0.3 from /usr/local/lib/python3.5/dist-packages (python 3.5)
```

**Comment by treyenelson** [comment]
@charris It was originally installed via pip.

Similar to @oxygenxo's situation, I had an older version of pip (9.0.1) and the previously installed version of numpy was likely two or three major versions behind.

Simply uninstalling numpy altogether before reinstalling v1.16.0 fixes the issue for me.

**Comment by kalbermattenm** [comment]
I just bumped into the same issue, but I had the latest versions of pip (18.1) and numpy (1.15.4) (on Windows). It looks like something goes wrong in the pip upgrade process.

Completely uninstalling / reinstalling numpy seems effectively to solve it.

**Comment by mattip** [comment]
Might it be that pip is not removing the `multiarray`, `umath` c-extension modules when upgrading? Since we unified them into one c-extension module `_multiarray_umath`, we created pure-python shims. But if there is a python file `name.py` and a c-extension module `name.so` or `name.pyd`, the c-extension module will be given preference.

**Comment by mattip** [comment]
You have a numpy in your image and you `pip install` another one or do you `pip install --upgrade`?

**Comment by kalbermattenm** [comment]
I did a `pip install -r ...` with an updated requirement file which is automatically updated through greenkeeper.

**Comment by mattip** [comment]
I am not a pip expert, is `pip install -r <file>` supposed to call `uninstall` when it discovers a stale version?

**Comment by charris** [comment]
I suspect this problem is longstanding, but invisible until we added the attribute to `ndarray` and used it in `_methods.py`.

**Comment by charris** [comment]
Hmm, the troublesome line is gone in master. AFAICT, `_NDARRAY_ARRAY_FUNCTION` defined in that file is not used anywhere. @shoyer is that a development artifact that got left behind?

**Comment by mattip** [comment]
[Pip documentation](https://pip.pypa.io/en/stable/user_guide/#uninstalling-packages) says they uninstall before installing a new version. But maybe the older version is from an `apt-get`, not `pip`?

**Comment by mattip** [comment]
@charris it is in the 1.16.0 tagged version of [`_methods.py`](https://github.com/numpy/numpy/blob/v1.16.0/numpy/core/_methods.py#L158). Note this is just a symptom of a broken installation, and a good one since it may be hard to detect they are using old c-extensions without that crash

**Comment by mattip** [comment]
@kalbermattenm, @treyenelson, @oxygenxo: was the old version `pip`-installed or was it part of some other installation (`apt`, `yum`, anaconda, ...)

**Comment by oxygenxo** [comment]
> You have a numpy in your image and you `pip install` another one or do you `pip install --upgrade`?

I'm not sure, in my case it looks like this:
```
12:58:49 Collecting numpy>=1.13.3 (from tensorflow==1.12.0)
12:58:50   Downloading https://files.pythonhosted.org/packages/64/24/2e9c72f44cec8c872000d78c54230e40550c494647e352d1d06724cdaee6/numpy-1.16.0-cp35-cp35m-manylinux1_x86_64.whl (17.2MB)
```
and then:
```
12:59:19 Installing collected packages: wheel, numpy, six, setuptools, protobuf, keras-preprocessing, gast, termcolor, grpcio, werkzeug, markdown, tensorboard, astor, h5py, keras-applications, absl-py, tensorflow
```
There was no `uninstall numpy 1.13.1` or so.

**Comment by treyenelson** [comment]
@mattip I'm fairly confident that it was pip installed.

**Comment by mattip** [comment]
@oxygenxo yes, `-I` means `--ignore-installed` so it does not do the right thing.

**Comment by mattip** [comment]
@treyenelson can you recreate the command you used to install 1.16?

**Comment by treyenelson** [comment]
@mattip It wasn't anything special. I was double checking that my project was installed using 
`pip install -e .`
The setup.py file includes this line:
`install_requires=['pyquaternion', 'numpy', 'pillow']`
Which caused it to upgrade from some previous version of numpy to the latest 1.16.0 and then fail trying to import numpy.
I then tried various commands, `pip install -r requirements.txt` (which includes simply `numpy`), `pip install numpy==1.16.0`, which all suffered from the same error when I tried importing numpy in the REPL. I then tried reverting back to the last release, `pip install numpy==1.15.4`, which imported just fine.
I also tried installing the latest numpy in a virtualenv that also had a previous version installed, but had the same result.
Once I simply ran `pip uninstall numpy`, I was able to run `pip install -e .` and use numpy 1.16.0 without problem.

**Comment by mattip** [comment]
@treyenelson `pip install -e .` should have uninstalled numpy before installing the new one. It would be nice to know why that didn't happen, although it sounds like a pip error, not a numpy one.

**Comment by jezzymodo** [comment]
I was having the same issue. I uninstalled v1.16 and installed v1.15.4 and it imported numpy without issue

**Comment by charlie718y** [comment]
I have the same issue, the workaround that worked for me is,

Assuming (appA depends on numpy)
1) After you install appA (this will automatically install numpy-1.16) <-- you see _AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'_ on execution
2) pip uninstall numpy
3) pip install numpy (numpy-1.16 will be installed, however this install works..)

**Comment by mattip** [comment]
@jezzymodo and others: please give us more information so we can help solve this. Clearly uninstalling and reinstalling works. What exactly did you do that failed? My suspicion falls on `pip install <various flags>`, where the flags are not uninstalling an older numpy before installing 1.16. For instance, these are known to be problematic:
```
pip install -r <file>
```
or 
```
pip install -e .
```

**Comment by jezzymodo** [comment]
HI @mattip,

I installed Numpy 1.16 via pip in powershell using the command 

> python -m pip install numpy

it installed v1.16 and once import was attempted in IDLE it failed with the error 
"AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'"

I uninstalled it using the same method and installed again which threw up the same error.

Reverting to v1.15.4 suggesting by @treyenelson "fixed" the issue

Apologies for bad formatting/explanation, I'm a relative noob to programming and github

**Comment by mattip** [comment]
@jezzymodo where did you get python from? Do you perhaps have another python process running on your machine that may have locked the 1.15.4 `multiarray.pyd` file, which would not allow the update to happen cleanly (on windows, linux does not have this problem)? You can check this by running `python -mpip uninstall numpy` to remove the 1.15.4 version, (which should complain if it cannot remove the file) before installing 1.16.0

**Comment by jezzymodo** [comment]
I downloaded python from here: https://www.python.org/downloads/

I just unistalled v1.15.4 and reinstalled v1.16 and it's now importing without issue

**Comment by skflowne** [comment]
I'm a python noob but this might help.

I got this error and at first I couldn't make it work with 1.16, so I went back to 1.15.4, this was working until I installed quandl which updated numpy to 1.16 again.

Then I had the error again, I installed 1.15.4 and it worked again

Then I tried uninstalling 1.15.4 and installing 1.16 and it worked also, not sure why it didn't at first but I'm using jupyter-notebook so maybe something wasn't taken into account.

My point is a dependency update through another package seems to also cause the problem.

**Comment by tzickel** [comment]
Can anybody with the issue write the output of this from the python runtime with the error (if it works):
```python
>>> import sys
>>> sys.path
['', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-x86_64-linux-gnu', '/usr/lib/python3.5/lib-dynload', '/root/.local/lib/python3.5/site-packages', '/usr/local/lib/python3.5/dist-packages', '/usr/lib/python3/dist-packages']
>>> import numpy.core.multiarray
>>> numpy.core.multiarray
<module 'numpy.core.multiarray' from '/usr/local/lib/python3.5/dist-packages/numpy/core/multiarray.py'>
>>> import pip
>>> pip.__version__
'9.0.3'
>>> import numpy.core
>>> numpy.core
<module 'numpy.core' from '/usr/local/lib/python3.5/dist-packages/numpy/core/__init__.py'>
>>> numpy.core.__version__
'1.16.0'
>>> import numpy
>>> numpy
<module 'numpy' from '/usr/local/lib/python3.5/dist-packages/numpy/__init__.py'>
```

also if when the error happens and you can't import numpy (nor run the commands above) if you run python -v and try to import numpy, this can insight to which files python is picking up (and paste it to a pastebin, maybe just greping the numpy lines there).

**Comment by dhiazfathra** [comment]
I got the same issue too. What I did to resolve this was simply run `pip uninstall numpy` several times until all installed version is uninstalled, then run `pip install numpy`

**Comment by aoife-doherty** [comment]
@dhiazfathra your answer was key for me. I did pip uninstall numpy and assumed numpy was uninstalled, and then when I did pip uninstall numpy again, I was surprised, I didn't realise that uninstall doesn't uninstall ALL copies of numpy just one...so I kept doing pip uninstall numpy until I had no more copies/versions, and then re-did pip install numpy, and it worked.

**Comment by mattip** [comment]
Note that many of the reporters are installing via `pip install --user`. Perhaps (credit to another user who tipped me off to this)

- they have a globally-installed numpy
- the file noted in the traceback, `numpy.core._methods` does not use relative imports, so it is picking up the preferred `multiarray` from `numpy.core` on the `sys.path`, and finds the non-`--user` NumPy installation's old c-extension module (since the import machinery looks first for c-extension modules)

**Comment by mattip** [comment]
Could one of the reporters with a broken installation modify the `_methods.py` file to print the location of the `multiarray` module (something like `/home/<username>/.local/lib/python3.6/site-packages/numpy/core/_methods.py`

```diff
from numpy.core import multiarray as mu
+print(mu)
from numpy.core import umath as um
from numpy.core.numeric import asanyarray
from numpy.core import numerictypes as nt
```

If the directory is not the same as the location of `_methods.py`, that would provide a smoking gun that the theory above is correct. Additionally, modifying `_method.py to use relative imports should then solve the problem.

```diff
import warnings

-from numpy.core import multiarray as mu
-from numpy.core import umath as um
+from . import multiarray as mu
+from . import umath as um
from numpy.core.numeric import asanyarray
from numpy.core import numerictypes as nt
from numpy._globals import _NoValue


```

**Comment by gryBox** [comment]
Hi - I just ran into this same problem (I think).  
`module initialization error: type object 'numpy.ndarray' has no attribute '__array_function__'`
It happens under isolated cases when I import `tetxacy 0.6.2`.
**No error:** 
1. jupyter notebook python 3.7.1 packaged by conda-forge | [GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
2.  python 3.6.5 (pip only installs) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

**Error:**
1. venv python 3.6.1, pip installs only [GCC 4.9.4]

@mattip The information you asked for I hope. 
`<module 'numpy.core.multiarray' from '/var/task/numpy/core/multiarray.cpython-36m-x86_64-linux-gnu.so'>`

Did not try your fix yet.

/cc @bdewilde

**Comment by njsmith** [comment]
I suspect that all issues people are reporting in this thread are cased by having used a sorta-broken method to install their previous version of numpy.

Pip does uninstall old versions before installing new ones. (Unless you explicitly tell it not to with some command-line option, like the `-I` used above.) But to do this, it relies on there being some metadata describing which files belong to the old version; otherwise, it doesn't know which files to remove.

Unfortunately, setuptools and easy_install *do not* save this metadata by default. Normal `pip install` invocations *do* record the metadata, but there are a bunch of different ways you could break this:

* if you install numpy using `python setup.py install` or `python setup.py develop`, then the metadata won't be recorded, and the next time you upgrade, things will be broken.

* If you install numpy via a `setup_requires=[...]` metadata, then that uses `easy_install`, which uses `setuptools`, which doesn't record metadata, so the next time you upgrade, things will be broken.

* "in place" installs internally require some gross hacks, which only setuptools knows how to do; so, if you use `pip install -e numpy`, then IIRC the metadata won't be recorded, and the next time you go to upgrade, things will be broken

* If you install your package using `python setup.py develop`, and your package has `install_requires=["numpy"]`, then setuptools will go ahead and use `easy_install` to install numpy, and things will be broken

* I'm not sure, but given the two points above, I wouldn't be too surprised if things also broke when you did `pip install -e your_package`, where `your_package` has `install_requires=["numpy"]`.

* If you get your packages from somewhere else, like apt or conda or something, then those packages may or may not include the metadata that pip needs, depending on whether the package maintainer used setuptools when building the package.

There's unfortunately not a lot that numpy can do about any of this... except I guess we could detect the issue manually at the beginning of import, and give a better error message.

We could even be systematic about it, and make sure that each release includes a `numpy/_markers/_v1_16_0_marker` file, and then at startup error out if there are any old marker files in the `numpy/_markers/` directory.

**Comment by treyenelson** [comment]
I'll just confirm that @njsmith is correct and that I can finally reproduce the error:

1. `pip uninstall numpy` until it fails (I had about 7 older versions installed it turns out)
2. In a project with `setup.py` containing `install_requires=['numpy==1.15.4']` run `pip install -e .` 
3. Run `pip install numpy==1.16.0`
4. Run `python -c "import numpy"`

And the result is the expected error:
`AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'`

**Comment by tzickel** [comment]
@treyenelson that does not reproduce on my end:
```
$ docker run -it --rm ubuntu:16.04
root@e018b708a68b:/# apt update && apt install python3-pip
...

root@e018b708a68b:/# cd
root@e018b708a68b:~# mkdir funniest
root@e018b708a68b:~# mkdir -p funniest/funniest
root@e018b708a68b:~# touch funniest/funniest/__init__.py
root@e018b708a68b:~# cat > funniest/setup.py <<EOF
> from setuptools import setup
>
> setup(name='funniest',
>       version='0.1',
>       description='The funniest joke in the world',
>       url='http://github.com/storborg/funniest',
>       author='Flying Circus',
>       author_email='flyingcircus@example.com',
>       license='MIT',
>       packages=['funniest'],
>       install_requires=['numpy==1.15.4'],
>       zip_safe=False)
> EOF
root@e018b708a68b:~# cd funniest/
root@e018b708a68b:~/funniest# pip3 install -e .
...
root@e018b708a68b:~/funniest# pip3 install numpy==1.16.0
Collecting numpy==1.16.0
  Downloading https://files.pythonhosted.org/packages/64/24/2e9c72f44cec8c872000d78c54230e40550c494647e352d1d06724cdaee6/numpy-1.16.0-cp35-cp35m-manylinux1_x86_64.whl (17.2MB)
    100% |################################| 17.2MB 62kB/s
Installing collected packages: numpy
  Found existing installation: numpy 1.15.4
    Uninstalling numpy-1.15.4:
      Successfully uninstalled numpy-1.15.4
Successfully installed numpy-1.16.0
...
root@e018b708a68b:~/funniest# python3 -c "import numpy"
root@e018b708a68b:~/funniest#
```

**Comment by mattip** [comment]
@whitty thanks. So now we have a smoking gun for the `--user` scenario. This is a `pip` issue that was fixed somewhere between pip 9.0.1, (which is what is installed with `apt install python-pip` on ubuntu 18.04), and pip 18.0. Note the `uninstalling` output when I use a newer pip to install 1.16.0 over 1.15.4:
```
$ python2 -mpip install --user numpy==1.16.0
Collecting numpy==1.16.0
  Using cached https://files.pythonhosted.org/packages/9f/85/163127d3fb0573deb9eca947cfc73aa3618eaaf8656501460574471d114a/numpy-1.16.0-cp27-cp27mu-manylinux1_x86_64.whl
Installing collected packages: numpy
  Found existing installation: numpy 1.15.4
    Uninstalling numpy-1.15.4:
      Successfully uninstalled numpy-1.15.4
Successfully installed numpy-1.16.0
```
We should recommend upgrading `pip` when doing `--user` installation:
```
python2 -mpip install --user --upgrade pip
```
This may solve the bulk of complaints, but @njs's other scenarios also leave previous installation cruft around

**Comment by charris** [comment]
This specific error will be fixed in 1.16.1 because the troublesome line was removed when `__array_function__` was moved to C.  However, it would still be useful if we be sure that the numpy imports were working properly everywhere and that we hadn't just made the error invisible.

**Comment by RneeJ** [comment]
I had same error, but could solve it with the above. Thanks for the input.

i'am new to Linux - Python etc, but maybe this helps other users .

I have Ubuntu 18.04. Later i Pip installed/upgrade numpy twice . A programm i used didn't run anymore, with the reported error.

I pip uninstalled twice versions 1.16 and 15.4.
 
With 3rd uninstall round pip gave notice 
" Not uninstalling numpy at /usr/lib/python2.7/dist-packages, outside environment /usr" 

It seems there is a default version, in Ubuntu/Synaptic says : 1:1.13.3-2ubuntu1
Pip can't upgrade/uninstall this.
With this default version everything works again.

**Comment by antadlp** [comment]
my problem was only inside jupyter, so I installed jupyter within my conda environment

$source activate env   # the environment with the problem
(env) $ conda install -c anaconda notebook

and the problem was solved (apparently it load the correct libraries of the environment)


note: my problem was when trying to load tensorflow in jupyter; numpy was installed together with tensorflow (1.12 version) using conda

**Comment by sometimescasey** [comment]
FWIW I got this error on a machine where I don't have admin permissions, and messing around with installing a user-specific pip and numpy just sent me in circles.

```
_NDARRAY_ARRAY_FUNCTION = mu.ndarray.__array_function__
AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'
```
In the end I resolved by just downgrading from numpy-1.16 to numpy-1.15.4.

**Comment by charris** [comment]
@sometimescasey I suspect that the underlying problem is still there, it just isn't visible.

**Comment by tzickel** [comment]
It's amazing that there is so much text here, but 0 reproduction... if someone can reproduce this in a clean docker environment, that could help.

It seems most complaints are on pip --user installation, and some are related to a numpy being installed via a dependency of anothe rproject.

**Comment by tzickel** [comment]
OK, I've finally reproduced the bug in an empty docker... the issue is when pip --user installing as a normal user, not root (which docker defaults to !!), also it's unrelated to if you have pyhton-numpy installed via apt or not:
```bash
$ docker run -it --rm ubuntu:18.04
root@cd025d48280b:/# apt update && apt install python-pip
...
root@cd025d48280b:/# adduser blah
...
root@cd025d48280b:/# su blah
...
blah@cd025d48280b:/$ pip install --user numpy==1.15.4
Collecting numpy==1.15.4
  Downloading https://files.pythonhosted.org/packages/de/37/fe7db552f4507f379d81dcb78e58e05030a8941757b1f664517d581b5553/numpy-1.15.4-cp27-cp27mu-manylinux1_x86_64.whl (13.8MB)
    100% |################################| 13.8MB 59kB/s
Installing collected packages: numpy
Successfully installed numpy-1.15.4
blah@cd025d48280b:/$ pip install --user numpy==1.16
Collecting numpy==1.16
  Downloading https://files.pythonhosted.org/packages/9f/85/163127d3fb0573deb9eca947cfc73aa3618eaaf8656501460574471d114a/numpy-1.16.0-cp27-cp27mu-manylinux1_x86_64.whl (17.0MB)
    100% |################################| 17.0MB 43kB/s
Installing collected packages: numpy
Successfully installed numpy-1.16.0
blah@cd025d48280b:/$ python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'
```

**Comment by mattip** [comment]
@tzickel  nice. 
If you update to pip 18 or above (19.1 was recently released) does the issue dissapear?

**Comment by elliothe** [comment]
test it!! there was multiple versions of numpy under "lib/python3.6/site-packages/"
The pip version I used is 19.0.1.
Steps I got it working are
1. keep running ```pip uninstall numpy```, until ```pip show numpy``` shows no numpy left.
2. Then reinstall the numpy through ```pip install -U numpy```

**Comment by pfmoore** [comment]
> installing pip in userland borks pip

That's an issue with Ubuntu's wrapper script (`/usr/bin/pip`) for pip. But it's not related to the `AttributeError` issue with numpy.

**Comment by tzickel** [comment]
Ok, had some time to mess with it. This is not related to the pip version itself, since when I just install python via apt, and bootstrap pip via the get-pip.py script to get the same version in ubuntu 18.04 and in the global dist-packages as well (which is 9.0.1) it works perfectly (installing both numpy version as a --user cleans up). So it's one of the following:
1. Something with how apt is installing python-pip.
2. The other dependencies that pip installs (setuptools, wheel) that are different (maybe related the same same, apt via pip).

**Comment by tzickel** [comment]
Ok, this is strange... if I didn't mess this up, on an empty ubuntu:18.04 installation:
1. apt pip 9.0.1, pip --user numpy 1.15.4, pip --user numpy 1.16 fails
2. apt pip 9.0.1, pip --user setuptools, pip --user wheel, pip --user numpy 1.15.4, pip --user numpy 1.16 fails
3. apt pip 9.0.1, pip --user pip, pip --user numpy 1.15.4, pip --user numpy 1.16 works
4. get-pip.py pip 9.0.1, pip --user numpy 1.15.4, pip --user numpy 1.16 works

**Comment by tzickel** [comment]
Ok, if you don't want to read everything I've written so far, here is the bug (IMHO). For some reason (don't know if it's a bug or not), debian's packaging of "python-pip" changes the original pip code of the same version (9.0.1) to enable the flag -I which causes it to ignore installed versions (and thus not removing the old numpy), when running as non-root and not in a virtualenvironment.

**Comment by mattip** [comment]
@tzickel if you get a chance, could you check that the fix in #12763 works (on the broken docker) 
```
pip install --user numpy==1.15.4
pip install --user git+git://github.com/numpy/numpy.git@f3f62d794c3
python -c "import numpy; numpy.test()"
```

**Comment by tzickel** [comment]
@mattip what about this solution: before importing multiarray, check the __file__ location of the __init__.py and just delete all multiarray files which are not .py/.pyc/.pyo in the same dir ?

**Comment by mattip** [comment]
@tzickel it seems a bit aggresive. I was aiming for a solution that
- does not incur a runtime penalty unless something is wrong
- warns the user something is wrong
- prompts the user to fix it themselves, I don't want to take responsibility for their installation

**Comment by tzickel** [comment]
I think the situation is aggressive, and that there are tons of numpy users which have no clue what numpy is, pip, venv or anything, and just use some script a friend did them to run some stuff, and now their situation is borked, and they won't know how to uninstall or run pip (if it's not in their path for example).

I agree with the "not incur a runtime penalty" but I think we are now in a trade-off mode, between fixing the situation for everyone an suffering some bit of I/O or having people which will be upset and not be able to do their work (the I/O can be measured for how bad it makes the import).

**Comment by tzickel** [comment]
another option. make multiarray_original.py and make an proxy multiarray.so like in the past, that just does the c-api equivalent of "from multiarray import *"

**Comment by mattip** [comment]
The suggested PR does something similar, but only after detecting and warning

**Comment by mattip** [comment]
Fixed PR #12763 to not overwrite the leftover c-extension module if it exists, so the correct commit to the docker check is 45ce0849a :
```
$ docker run -it --rm ubuntu:18.04
root@cd025d48280b:/# apt update && apt install python-pip git cython
...
root@cd025d48280b:/# adduser blah
...
root@cd025d48280b:/# su blah
blah@cd025d48280b:/$ pip install --user numpy==1.15.4
blah@cd025d48280b:/$ pip install --user pytest git+git://github.com/mattip/numpy.git@45ce0849a
blah@cd025d48280b:/$ python -Walways -c "import numpy; numpy.test()"
```
This should run tests to completion and report the warning "ImportWarning: Something is wrong with the NumPy installation. While importing 'multiarray' we detected an older version of numpy. One method of fixing this is to repeatedly 'pip uninstall' numpy until none is found, then reinstall this version. If you know how to recreate this error, please file an issue at https://github.com/numpy/numpy/issues and xref https://github.com/numpy/numpy/issues/12736"

**Comment by pfmoore** [comment]
This is a known bug in debian's changes to pip - see https://github.com/pypa/pip/issues/4222.

**Comment by pradyunsg** [comment]
> https://github.com/numpy/numpy/issues/12736#issuecomment-456970334

Instead of installing with apt, does this issue reproduce with pip installed using `curl https://bootstrap.pypa.io/get-pip.py | python -- --user`?

**Comment by pfmoore** [comment]
> This is a known bug in debian's changes to pip - see pypa/pip#4222.

Sorry, I see that @tzickel already identified that, in https://github.com/numpy/numpy/issues/12736#issuecomment-457097276

**Comment by pradyunsg** [comment]
Can confirm this doesn't occur with vanilla pip, it's due to debian's patch, as @pfmoore and @tzickel noted.

```sh-session
root@2a4684db45a6:/# adduser blah
[snip]
root@2a4684db45a6:/# su blah
blah@2a4684db45a6:/$ curl -sSL https://bootstrap.pypa.io/get-pip.py | python -- --user
[snip]
blah@2a4684db45a6:/$ python -m pip install --user numpy==1.15.4
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting numpy==1.15.4
  Downloading https://files.pythonhosted.org/packages/de/37/fe7db552f4507f379d81dcb78e58e05030a8941757b1f664517d581b5553/numpy-1.15.4-cp27-cp27mu-manylinux1_x86_64.whl (13.8MB)
    100% |################################| 13.8MB 385kB/s
Installing collected packages: numpy
Successfully installed numpy-1.15.4
blah@2a4684db45a6:/$ python -m pip install --user numpy==1.16
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting numpy==1.16
  Downloading https://files.pythonhosted.org/packages/9f/85/163127d3fb0573deb9eca947cfc73aa3618eaaf8656501460574471d114a/numpy-1.16.0-cp27-cp27mu-manylinux1_x86_64.whl (17.0MB)
    100% |################################| 17.0MB 476kB/s
Installing collected packages: numpy
  Found existing installation: numpy 1.15.4
    Uninstalling numpy-1.15.4:
      Successfully uninstalled numpy-1.15.4
  The scripts f2py, f2py2 and f2py2.7 are installed in '/home/blah/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed numpy-1.16.0
blah@2a4684db45a6:/$ python -c "import numpy"
blah@2a4684db45a6:/$
```

**Comment by tzickel** [comment]
The PR seems to work ok. I would just word the error message differently.

**Comment by wenzao** [comment]
My `numpy` is installed by `conda`, not `pip`, and I also have this same problem.

```
In [1]: import numpy as np                                                      
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-0aa0b027fcb6> in <module>
----> 1 import numpy as np

~/miniconda3/lib/python3.6/site-packages/numpy/__init__.py in <module>
    140     from . import _distributor_init
    141 
--> 142     from . import core
    143     from .core import *
    144     from . import compat

~/miniconda3/lib/python3.6/site-packages/numpy/core/__init__.py in <module>
     57 from . import numerictypes as nt
     58 multiarray.set_typeDict(nt.sctypeDict)
---> 59 from . import numeric
     60 from .numeric import *
     61 from . import fromnumeric

~/miniconda3/lib/python3.6/site-packages/numpy/core/numeric.py in <module>
   3091 from .umath import *
   3092 from .numerictypes import *
-> 3093 from . import fromnumeric
   3094 from .fromnumeric import *
   3095 from . import arrayprint

~/miniconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py in <module>
     15 from . import numerictypes as nt
     16 from .numeric import asarray, array, asanyarray, concatenate
---> 17 from . import _methods
     18 
     19 _dt_ = nt.sctype2char

~/miniconda3/lib/python3.6/site-packages/numpy/core/_methods.py in <module>
    156     )
    157 
--> 158 _NDARRAY_ARRAY_FUNCTION = mu.ndarray.__array_function__
    159 
    160 def _array_function(self, func, types, args, kwargs):

AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'

```

**Comment by dmitriyshashkin** [comment]
I also had the same problem with pip from conda

**Comment by tzickel** [comment]
Yes, but without giving us more information such as a reproduction or by minimum the conda + pip versions and how did it happen, it doesn't help too much.

**Comment by wenzao** [comment]
I rolled back to v1.15 and it's working now.

**Comment by tzickel** [comment]
@wenzao you have numpy-base 1.15.4 and numpy 1.16 that is the core of the issue...

**Comment by bwanglzu** [comment]
@elliothe thanks you saved my day!
1. sudo pip3 uninstall numpy
2. sudo pip3 uninstall numpy
.... do this until you can not uninstall numpy anymore
3. sudo pip3 install -U numpy

ubuntu 18.04, python 3.5.

**Comment by kellyfj** [comment]
> @elliothe thanks you saved my day!
> 
> 1. sudo pip3 uninstall numpy
> 2. sudo pip3 uninstall numpy
>    .... do this until you can not uninstall numpy anymore
> 3. sudo pip3 install -U numpy
> 
> ubuntu 18.04, python 3.5.

This sequence of successive uninstalls fixed it for me

**Comment by mattip** [comment]
Closing. We now detect this and emit a better error message.

**Comment by amureki** [comment]
Just a small update for everyone who is using Travis and struggling with this issue and can't figure out the root cause (as we did).

Travis preinstalls 1.15.2 on Trusty and Precise build environments:
https://docs.travis-ci.com/user/reference/precise
https://docs.travis-ci.com/user/reference/trusty
(search for numpy)

So, as advised above, the next Travis config will help you:
```
before_install:
# Travis pre-installs an old version of numpy.
# It conflicts with the latest one, see https://github.com/numpy/numpy/issues/12736
- pip uninstall -y numpy # will uninstall your numpy from cache
- pip uninstall -y numpy # will uninstall preinstalled numpy 1.15.2
- pip uninstall -y numpy # just in case
```

I cannot say I am happy with this workaround, but until Travis will update their build packs we can do nothing.

**Comment by deepsach** [comment]
![IMG-20200605-WA0021](https://user-images.githubusercontent.com/66744405/84386216-9060bd00-ac0e-11ea-99f4-e92593848991.jpg)
I get this error while import pandas in python
numpy has no Version module

**Comment by Soul0702** [comment]
(voice-clone) C:\Users\DELL\Desktop\voice>python demo_cli.py
Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\voice\demo_cli.py", line 5, in <module>
    import librosa
  File "C:\Users\DELL\anaconda3\envs\voice-clone\Lib\site-packages\librosa\__init__.py", line 211, in <module>
    from . import core
  File "C:\Users\DELL\anaconda3\envs\voice-clone\Lib\site-packages\librosa\core\__init__.py", line 9, in <module>
    from .constantq import *  # pylint: disable=wildcard-import
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\anaconda3\envs\voice-clone\Lib\site-packages\librosa\core\constantq.py", line 1058, in <module>
    dtype=np.complex,
          ^^^^^^^^^^
  File "C:\Users\DELL\anaconda3\envs\voice-clone\Lib\site-packages\numpy\__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'complex'.
`np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'complex_'?
