### ISSUE TITLE
"File size unexpectedly exceeded ZIP64 limit" error when trying to save a dict with huge array

### ISSUE THREAD

**Issue by belltailjp** [numpy/numpy#13153]
Hi!
I found that `np.savez` mistakenly deals with saving large npz when the data is a dict (specifically, mistakenly set the `force_zip64` flag), which results in the "File size unexpectedly exceeded ZIP64 limit" error.

### Reproducing code example:

```python
import numpy as np

np.savez('hoge.npz', {'a': np.random.rand(1024, 1024, 256)})
```

### Error message:

When I run the above code in REPL, 

```
In [0]: import numpy as np
In [1]: np.savez('hoge.npz', {'a': np.random.rand(1024, 1024, 256)})
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)                       
<ipython-input-3-572e3cc1d32c> in <module>()        
----> 1 np.savez('hoge.npz', {'a': np.random.rand(1024, 1024, 256)}) 
                                                                       
~/Gomi/numpy/numpy/core/overrides.py in public_api(*args, **kwargs)
    148             relevant_args = dispatcher(*args, **kwargs)                   
    149             return implement_array_function(
--> 150                 implementation, public_api, relevant_args, args, kwargs)
    151                                
    152         if module is not None:                   
                                                                                       
~/Gomi/numpy/numpy/lib/npyio.py in savez(file, *args, **kwds)
    621                                                      
    622     """
--> 623     _savez(file, args, kwds, False)              
    624
    625                                                         
                                                                           
~/Gomi/numpy/numpy/lib/npyio.py in _savez(file, args, kwds, compress, allow_pickle, pickle_kwargs)
    730                 format.write_array(fid, val,
    731                                    allow_pickle=allow_pickle,
--> 732                                    pickle_kwargs=pickle_kwargs)
    733     else:
    734         # Stage arrays in a temporary file on disk, before writing to zip.

~/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/zipfile.py in close(self)
   1018             if not self._zip64:
   1019                 if self._file_size > ZIP64_LIMIT:
-> 1020                     raise RuntimeError('File size unexpectedly exceeded ZIP64 '
   1021                                        'limit')
   1022                 if self._compress_size > ZIP64_LIMIT:

RuntimeError: File size unexpectedly exceeded ZIP64 limit
```

If the array I try to save doesn't exceed 2GB, it doesn't fail.
```
np.savez('hoge.npz', {'a': np.random.rand(1024, 1024, 128)})    # 1GB --> OK
```

Also, if I don't use a dict there's no problem either, no matter how large it is.
```
np.savez('hoge.npz', np.random.rand(1024, 1024, 1024))    # 8GB --> OK
```

The problem I have figured out is that npyio doesn't correctly recognize how large the data is, consequently it fails to force `force_zip64` mode.
https://github.com/numpy/numpy/blob/d89c4c7e7850578e5ee61e3e09abd86318906975/numpy/lib/npyio.py#L728
This line tries to find the memory consumption of the array through `nbytes`, but with an numpy-array-nized dict it doesn't bahave as expected.

```
In [21]: a = {'a': np.random.rand(1024, 1024, 128)}
In [22]: a_np = np.asarray(a)
In [23]: a_np.nbytes
Out[23]: 8
```

I'm not sure this problem is in whether `nbytes` in np.array or `_savez`, but I think it needs some modifications so that it can correctly get the size of child arrays in a dict.

If I forcibly modify the `zipf.open` line like below, my code goes well with no problem (I guess conditional `force_zip64` is kept due to some compatibility concerns, though).
```
with zipf.open(fname, 'w', force_zip64=True) as fid:
```

### Numpy/Python version information:

I confirmed the above phenomenon with:
```
1.16.1 3.7.1 | packaged by conda-forge | (default, Nov 13 2018, 18:33:04)
[GCC 7.3.0]
```
and (the current master)
```
1.17.0.dev0+d89c4c7 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49)                                                    
[GCC 7.2.0]
```

**Comment by belltailjp** [comment]
I checked https://github.com/numpy/numpy/issues/10776.
The same phenomenon seems to be also happening with np.array-nized list of np.array.

```
> test_data = np.asarray([np.random.rand(np.random.randint(50,100),4) for i in range(800000)]) 
> test_data.shape
(800000,)
> test_data.nbytes
6400000                  # smaller than 2**30, so force_zip64 becomes False, however....
> sum(a.nbytes for a in test_data)
1906662432            # the actual data is larger than 2**30, so the error happens
```

**Comment by YubinXie** [comment]
When I use np.savez for large array, this error happens.
When I use np.save for larger array, another size related error happens... 
```

~/miniconda3/lib/python3.6/site-packages/numpy/lib/npyio.py in save(file, arr, allow_pickle, fix_imports)
    527         arr = np.asanyarray(arr)
    528         format.write_array(fid, arr, allow_pickle=allow_pickle,
--> 529                            pickle_kwargs=pickle_kwargs)
    530     finally:
    531         if own_fid:

~/miniconda3/lib/python3.6/site-packages/numpy/lib/format.py in write_array(fp, array, version, allow_pickle, pickle_kwargs)
    627         if pickle_kwargs is None:
    628             pickle_kwargs = {}
--> 629         pickle.dump(array, fp, protocol=2, **pickle_kwargs)
    630     elif array.flags.f_contiguous and not array.flags.c_contiguous:
    631         if isfileobj(fp):

OSError: [Errno 22] Invalid argument
```

**Comment by mattip** [comment]
xref #12428 which is still waiting to be merged

**Comment by YubinXie** [comment]
I updated Python to 3.7 and it is resolved...

**Comment by jamesmkrieger** [comment]
I am using Python 3.7.2 with numpy 1.16.4 and I still have this issue.

**Comment by icmpnorequest** [comment]
I am using Python3.6 with Numpy 1.16.4 on Google Colab, I still have this issue.

**Comment by mattip** [comment]
Can you test with NumPy 1.17?

**Comment by icmpnorequest** [comment]
> Can you test with NumPy 1.17?

I changed to use `np.save` instead of `np.savez`, and it works with NumPy 1.16.4.

**Comment by jamesmkrieger** [comment]
Thanks. I'll see if that helps me to.

**Comment by mattip** [comment]
Closing based on a comment above. Please reopen if needed.
