### ISSUE TITLE
Getting No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by abhinavsagar** [numpy/numpy#13554]
I am trying to write a simple ai game using pygame. On running, I am getting-
`ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ImportError: numpy.core.multiarray failed to import`
.
.

### Numpy/Python version information:

Python - 3.6.5
Numpy - 1.15.0

**Comment by charris** [comment]
Sounds like you are actually running NumPy 1.16. How did you install NumPy? There were many issues involving Anaconda, see #12736 for instance, that have been resolved with updating or removing old multiple versions of NumPy.

**Comment by abhinavsagar** [comment]
@charris I am running 1.16. I have used pip install numpy. To no avail even after spending a couple of hours on stackoverflow I am still not able to debug this.

**Comment by mattip** [comment]
The actual error contains much more information. Please post the entire error traceback

**Comment by abhinavsagar** [comment]
Here is the complete error-
`ImportError                               Traceback (most recent call last)
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
c:\users\win 10\appdata\local\programs\python\python36\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set`

**Comment by mattip** [comment]
The complete error should begin with `IMPORTANT: PLEASE READ THIS`.

**Comment by abhinavsagar** [comment]
@mattip It is working now. I reinstalled numpy and then installed using conda. Thanks for the help.

**Comment by oleg-alexandrov** [comment]
It is important that "which python" should return the path to python from the environment having the numpy installed with conda, rather than the python from a different conda environment or from the base environment, even if the version of the two pythons is the same. I ran into the same problem and this was the fix for me.
