### ISSUE TITLE
Misleading error message with object dtype

### ISSUE THREAD

**Issue by AllenDowney** [numpy/numpy#13666]
Many NumPy methods fail if an array has dtype object, and produce a misleading error message.

Based on StackOverflow, other people found the message confusing:
https://stackoverflow.com/questions/18557337/numpy-attributeerror-float-object-has-no-attribute-exp
https://stackoverflow.com/questions/49971708/python-numpy-attributeerror-float-object-has-no-attribute-sin
https://stackoverflow.com/questions/49662823/different-behavior-of-arithmetics-on-dtype-float-object-and-float

And here's a related previous issue:
https://github.com/numpy/numpy/issues/8357

I agree with eric-weiser that the error should be a TypeError, since the problem is the dtype of the array.
```
TypeError: Cannot call log10 on an object array
```
Alternatively, these funcs could try to convert object arrays to numeric.

### Reproducing code example:

```python
import numpy as np
a = np.array([1,2,3], dtype=object)
np.sqrt(a)
```

### Error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'int' object has no attribute 'sqrt'
```

### Numpy/Python version information:

```
1.16.3 3.7.3 | packaged by conda-forge | (default, Mar 27 2019, 23:01:00) 
[GCC 7.3.0]
```

**Comment by oribro** [comment]
Hi,
So I tried to reproduce the error using @AllenDowney 's  example and got this error message:

```
>>> a = np.array([1,2,3], dtype=object)
>>> a
array([1, 2, 3], dtype=object)
>>> np.sqrt(a)
AttributeError: 'int' object has no attribute 'sqrt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: loop of ufunc does not support argument 0 of type int which has no callable sqrt method
```


My numpy version is `1.17.0.dev0+9713e86` and I'm using:
```
Python 3.6.8 (default, Dec 24 2018, 19:24:27) 
[GCC 5.4.0 20160609] on linux
```

Is the issue fixed in numpy's latest version? 
If not, I'd like to try and write a proper error message for the object dtype functions if that's acceptable.
Any idea where should I look for in the code?

Thanks!

**Comment by eric-wieser** [comment]
Looks like we already fixed this. Thanks for testing @oribro!

**Comment by eric-wieser** [comment]
Fixed in #12700

**Comment by oribro** [comment]
@eric-wieser Nice! I'm glad I could help

**Comment by NikAmbr** [comment]
After cloning numpy repo I still face this error. Numpy version :1.19.0.dev0+8e3062d What can I do?

**Comment by mirkhosro** [comment]
Hello. This issue seems to be still there in version '1.18.4' of numpy.
Same code as above reproduces the error
```
import numpy as np
a = np.array([1,2,3], dtype=object)
np.sqrt(a)
AttributeError: 'int' object has no attribute 'sqrt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3291, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-bf82c876ab7f>", line 3, in <module>
    np.sqrt(a)
TypeError: loop of ufunc does not support argument 0 of type int which has no callable sqrt method
```

**Comment by seberg** [comment]
@mirkhosro the error message tries to explain what is going on here. That for object arrays, in most cases these ufuncs will not work (unless the objects happen to have the correct method).

Improvements to the message are welcome! But I am not sure I have an idea to be honest.

**Comment by mirkhosro** [comment]
the error message may be helpful for numpy developers but is still cryptic for numpy users who have no idea what `ufunc` is or which `loop` it's referring to.
You're right, it's probably not easy to come up with a better message. I just wanted to inform you that from a user point-of-view it's still not very useful, and took me Googling around to find out what was going on.

**Comment by eric-wieser** [comment]
Perhaps simply
```
TypeError: object loop of 'sqrt' ufunc does not support argument 0 of type int which has no callable sqrt method
```

**Comment by janosh** [comment]
Just stumbled over this with a `pd.Series` by calling `proba_pos.round()` where

```py
proba_pos = [0.386319, ... , 0.403257]
Name: softmax_1, dtype: object
```

throws

```
TypeError: loop of ufunc does not support argument 0 of type numpy.float32 which has no callable rint method
```

I agree with @AllenDowney and @eric-wieser that a clearer error message would be great here. How about something like:

> Calling `.round()` on an array with `dtype=object` is not supported. Perhaps convert to `float`?

**Comment by ctwardy** [comment]
FYI: Just ran into this calling Pandas' DataFrame.plot.scatter() and passing a column of UInt8 or Float64 as the size parameter `s`.  I had to explicitly cast to `float16`. Strange because I can do `np.sqrt(df['magnitude'])` on either UInt8 or Float64, but passing 'magnitude' to the `scatter()` function threw this error saying either 'int' or 'float' lack 'sqrt' method.

**Comment by HPrinzhorn** [comment]
I had the same issue. Then I converted the columns from object dtype to float32 like shown [https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.astype.html](here). End of the story.
