### ISSUE TITLE
Recent Travis 3.9dev tests failing due to Unicode deprecations

### ISSUE THREAD

**Issue by seberg** [numpy/numpy#16640]
It seems that Python decided to deprecate some of the Unicode macros, which we use in our py3k compat, see https://travis-ci.org/github/numpy/numpy/jobs/700240806#L4473 for a run which failed due to these.

**Comment by eric-wieser** [comment]
```
numpy/core/src/multiarray/ctors.c:2365:5: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
  numpy/core/src/multiarray/ctors.c:2365:5: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
  numpy/core/src/multiarray/ctors.c:2365:5: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
  numpy/core/src/multiarray/descriptor.c:472:9: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
  numpy/core/src/multiarray/descriptor.c:472:9: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
  numpy/core/src/multiarray/descriptor.c:472:9: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
  numpy/core/src/multiarray/descriptor.c:481:13: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
  numpy/core/src/multiarray/descriptor.c:481:13: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
  numpy/core/src/multiarray/descriptor.c:481:13: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
  numpy/core/src/multiarray/scalarapi.c:144:13: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
  numpy/core/src/multiarray/scalartypes.c.src:369:5: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
  numpy/core/src/multiarray/scalartypes.c.src:370:5: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
  numpy/core/src/multiarray/scalartypes.c.src:370:5: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
  numpy/core/src/multiarray/scalartypes.c.src:370:5: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
  numpy/core/src/multiarray/scalartypes.c.src:375:5: warning: ‘PyUnicode_FromUnicode’ is deprecated [-Wdeprecated-declarations]
  numpy/core/src/multiarray/scalartypes.c.src:369:5: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
  numpy/core/src/multiarray/scalartypes.c.src:370:5: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
  numpy/core/src/multiarray/scalartypes.c.src:370:5: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
  numpy/core/src/multiarray/scalartypes.c.src:370:5: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
  numpy/core/src/multiarray/scalartypes.c.src:375:5: warning: ‘PyUnicode_FromUnicode’ is deprecated [-Wdeprecated-declarations]
  numpy/random/_generator.c:43239:9: warning: ‘PyUnicode_FromUnicode’ is deprecated [-Wdeprecated-declarations]
```

**Comment by eric-wieser** [comment]
I'd hoped that my UCS4 change a few months ago has cleaned out all these, but I guess I either missed one or decided they couldn't cause bugs.

**Comment by eric-wieser** [comment]
xref #11699

**Comment by seberg** [comment]
I think its likely that the only issue is `#define PyUString_GET_SIZE PyUnicode_GET_SIZE` which should use `PyUnicode_GET_LENGTH` (or maybe users of that macro should just use it directly).

**Comment by eric-wieser** [comment]
The ones in `scalartypes.c.src` are the functions which are affected by #15477, which I think I ignored in my previous pass because the behavior was weird already.

**Comment by eric-wieser** [comment]
The one in `scalarapi.c` is a bug that manifests for subclasses of `str_`.

**Comment by mattip** [comment]
It seems we have no tests that hit the line `scalarapi.c:144` (or maybe I am missing something?) - the use is only in untested parts of the NumPy C-API.

**Comment by seberg** [comment]
@mattip is it possible you are in my array-coercion branch? I think up until that `PyArray_FromScalar` used it, but I stopped using it in that branch at this time (i just unconditionally use `->setitem` or do the casting slightly different in `PyArray_Pack()`.

**Comment by seberg** [comment]
@mattip sorry, nvm... I was thinking of the `scalar_value` function completely... My guess is that this is being used for user-dtypes in theory (and probably also in practice, I am surprised this is never hit in the rational tests).  Where we would assume that the user dtype has a memory layout of:
```
PyObject_HEAD;
ob_val;
```

**Comment by seberg** [comment]
Ahhh, and user-dtypes are supposed to *always* use the `NPY_USE_GETITEM` and `NPY_USE_SETITEM` flag, so this also basically takes them out of the picture, making the code indeed unreachable for any properly defined user-dtype.

**Comment by eric-wieser** [comment]
Isn't this code path for scalar subclasses?

**Comment by seberg** [comment]
Hmmm, its strange, it seems like a fallback to a fallback?  And even the first fallback for subclasses seems fairly unreachable, because the `dtype` we report for a subclass should be identical to the dtype of the superclass?

**Comment by eric-wieser** [comment]
Is the one in `_generator.c` something that needs fixing in cython?

**Comment by mattip** [comment]
> Is the one in `_generator.c` something that needs fixing in cython?

It has been fixed on master apparently, but not yet in a release.

**Comment by seberg** [comment]
Ok, so this is all super scary stuff, except for built-in `np.generic` subclasses.  There is a reason, why in my new branch, I only used `setitem` and `getitem`, those are at least well defined.  Everything else requires us to define how a scalar looks like exactly.  Which is nice, but really feels like a lot of complexity for little gain (yes, you can access the low-level data directly, but so can `setitem` and it only has to do one type check first).  Of course you might have to do one allocation, that actually is not nice, but in most cases you could do that on the heap even (`PyArray_Pack` currently does not, and it is *still* much faster I think).

Not that I did not list them before somewhere, but list of the scary users (the scariest are the ones that do not have the capability to return an error:
```
gentype_byteswap
gentype_imag_get
gentype_real_get
FillWithScalar, 
PyArray_CastScalarDirect,
PyArray_ScalarAsCtype,
PyArray_CastScalarToCtype,
PyArray_FromScalar,
PyArray_FillWithScalar,
```

Now subclasses *should* normally report the same `dtype`, but I guess they don't have to specifically, if they are registered to belong to a user defined dtype, then they will *not* match.  I expect a user defined string dtype cannot really work though, because there are too many checks where we use the type numbers to decide that something is flexible probably...

So: The only places where this *should* happen is scary C-API functions, and it is true that within NumPy, probably `setitem` and `getitem` should be used everywhere, although `PyArray_FillWithScalar` seems to have a different opinion.

**Comment by charris** [comment]
> It has been fixed on master apparently, but not yet in a release.

I installed cython from master in Python 3.9 and still see the problem.

**Comment by charris** [comment]
Correction, Cython 3.0a4 does fix the random module issues. Remaining is the `scalar_value` function in `numpy/core/src/multiarray/scalarapi.c`. That one is hard to figure out, should unicode data always be returned as ucs4 (NumPy standard), or should it depend on the conversion to canonical form, or should it depend on the old `Py_UNICODE_SIZE`. The problem is that we need to choose one of the four options. The other problem is that if we convert a canonical object we may get an error and errors are not checked for.

**Comment by eric-wieser** [comment]
> That one is hard to figure out, should unicode data always be returned as ucs4 (NumPy standard), or should it depend on the conversion to canonical form, or should it depend on the old `Py_UNICODE_SIZE`

As discussed elsewhere, that code path is very hard to reach. That's taken only for custom dtypes which have scalars which subclass `np.str_`.

For regular `np.str_` types, UCS4 is already returned in a fast path above.

**Comment by charris** [comment]
I put up #16750 for discussion. The fast path may return NULL, which is not checked for AFAICT.

**Comment by hugovk** [comment]
These are documented in [PEP 623](https://www.python.org/dev/peps/pep-0623/).

(And [PEP 624](https://www.python.org/dev/peps/pep-0624/) deprecates `Py_UNICODE` encoder APIs.)

**Comment by seberg** [comment]
Closing this for now, I think @charris fixed all the problematic cases.  I will try and see if I can delete `scalar_value` aside from obviously harmless use (ideally most of those could then be replaced with a more specific look-up though).
