### ISSUE TITLE
md5sum of numpy-1.19.0.tar.gz does not match the reality

### ISSUE THREAD

**Issue by dimpase** [numpy/numpy#16754]
### Reproducing code example:

Download  https://github.com/numpy/numpy/archive/v1.19.0.tar.gz and check that its md5sum has changed.
Namely, it is `e3baa59da67348c2d6596803514129db`
and not what the release page says, d59aadf47354bd10c7b9996032ba4da0

Probably it's another instance of unstable GitHub-generated tarballs. The usual fix would be to manually (or otherwise) edit the release and upload a tarball as a "binary asset".

**Comment by dimpase** [comment]
and, 5 min later, it's d59aadf47354bd10c7b9996032ba4da0 - as advertised.

**Comment by rossbar** [comment]
Seems like this is resolved - closing. Please feel free to re-open if the problem reappears.

**Comment by dimpase** [comment]
the problem is still there - in the sense that GitHub doesn't promise to
keep the md5 of tarballs stable.

**Comment by rossbar** [comment]
@charris I don't quite understand what's going on here, do you have any insights?

**Comment by rgommers** [comment]
So this is a "don't do that" kind of thing. This is about the GitHub auto-generated tarball (the "source code" link in the image below), which we unfortunately can't delete. But it's not what anyone should use, instead one should download the `sdist` that we upload (i.e. ` numpy-1.19.0.tar.gz`):

<img width="254" alt="image" src="https://user-images.githubusercontent.com/98330/87349153-23ff1380-c556-11ea-8ce2-5a7b83e6ac05.png">

**Comment by rossbar** [comment]
Thanks for clearing that up!

**Comment by dimpase** [comment]
Thanks, and sorry for confusion.

**Comment by rgommers** [comment]
no worries at all, thanks for reporting
