### ISSUE TITLE
setup_problem

### ISSUE THREAD

**Issue by lty-creator** [numpy/numpy#17557]
>>> import numpy
Python(11289,0x7fff8ee50380) malloc: *** mach_vm_map(size=18446744071557701632) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
init_dgelsd failed init
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/root/Library/Python/3.9/lib/python/site-packages/numpy/__init__.py", line 286, in <module>
    raise RuntimeError(msg)
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
RankWarning: Polyfit may be poorly conditioned

### Reproducing code example:

```python
import numpy as np
<< your code here >>
```

**Comment by mattip** [comment]
Please read the error message. 
> If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.

Since binary wheels are not available for python3.9, you compiled from source and must follow the directions in `site.cfg`

**Comment by hbxz** [comment]
If you are using python3.9, the easiest way to walk around this is to install an older version.
```bash
pip3 uninstall numpy -y
pip3 install numpy==1.18.0
```

**Comment by mattip** [comment]
The master branch improves the [error message](https://github.com/numpy/numpy/blob/master/numpy/__init__.py#L351) with a link to [the troubleshooting page](https://numpy.org/devdocs/user/troubleshooting-importerror.html?highlight=troubleshooting). Would that have helped you any more? We could improve that with a message on using `pip install --only-binary :all:`.

I wish that was the `pip` default, most people do not want to compile c-extension packages.

**Comment by lty-creator** [comment]
> Please read the error message.
> 
> > If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
> 
> Since binary wheels are not available for python3.9, you compiled from so

**Comment by lty-creator** [comment]
> Please read the error message.
> 
> > If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
> 
> Since binary wheels are not available for python3.9, you compiled from source and must follow the directions in `site.cfg`

Thanks for your advice

> If you are using python3.9, the easiest way to walk around this is to install an older version.
> 
> ```shell
> pip3 uninstall numpy -y
> pip3 install numpy==1.18.0
> ```
By installing 1.18.0, this problem have been solved. thank you very much

**Comment by lty-creator** [comment]
> The master branch improves the [error message](https://github.com/numpy/numpy/blob/master/numpy/__init__.py#L351) with a link to [the troubleshooting page](https://numpy.org/devdocs/user/troubleshooting-importerror.html?highlight=troubleshooting). Would that have helped you any more? We could improve that with a message on using `pip install --only-binary :all:`.
> 
> I wish that was the `pip` default, most people do not want to compile c-extension packages.

Thanks for your advice

**Comment by eric-wieser** [comment]
> By installing 1.18.0, this problem have been solved. thank you very much

As far as I remember, installing 1.18 will still have an issue with Accelerate, the only difference being it no longer tells you and refuses to install - instead it will produce numerically wrong results.

**Comment by mattip** [comment]
> As far as I remember, installing 1.18 will still have an issue with Accelerate

Not if they use the binary wheel which is compiled with OpenBLAS, `pip install --only-binary :all:` should make sure that happens.

**Comment by eric-wieser** [comment]
Right, but there is no binary for python 3.9?

**Comment by mattip** [comment]
Correct.
