### ISSUE TITLE
Polynomial can't be evaluated on list of numbers only ndarray of numbers

### ISSUE THREAD

**Issue by jjmortensen** [numpy/numpy#17949]
Is it on purpose that this doesn't work:

```python
>>> np.polynomial.Polynomial([1, 2])([3, 4])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jensj/.local/lib/python3.7/site-packages/numpy/polynomial/_polybase.py", line 482, in __call__
    arg = off + scl*arg
TypeError: can't multiply sequence by non-int of type 'numpy.float64'
```

but this does:

```python
>>> np.polynomial.Polynomial([1, 2])(np.array([3, 4]))
array([7., 9.])
```

**Comment by rossbar** [comment]
My feeling is that `__call__` should support array-likes, so this should be fixed.

**Comment by IngErnestoAlvarez** [comment]
It would be sufficient if it casts an array-like parameter to np.array inside the `__call__` function?

**Comment by WarrenWeckesser** [comment]
I just ran into this.  The issue still exists with the main development branch:

```
In [11]: np.__version__
Out[11]: '2.0.0.dev0+766.g8627dc962'

In [12]: p = np.polynomial.Polynomial([1, -2.5, 3, 1])

In [13]: p([2, 3, 4])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[13], line 1
----> 1 p([2, 3, 4])

File ~/repos/git/forks/numpy/build-install/usr/lib/python3.11/site-packages/numpy/polynomial/_polybase.py:512, in ABCPolyBase.__call__(self, arg)
    510 def __call__(self, arg):
    511     off, scl = pu.mapparms(self.domain, self.window)
--> 512     arg = off + scl*arg
    513     return self._val(arg, self.coef)

TypeError: can't multiply sequence by non-int of type 'numpy.float64'

```

**Comment by charris** [comment]
Polynomials can be evaluated on objects, matrices for example, and a list is just another object, but fails because it cannot be multiplied by floats (coefficients).
