### ISSUE TITLE
BUG: Refcnt leak on failure (some static analysis reports)

### ISSUE THREAD

**Issue by Snape3058** [numpy/numpy#21532]
Please give every report a confirmation result. Refer to a report with its ID (the hex numbers in the parenthesis) for simplicity.
If there are multiple hex numbers in the parenthesis, they are the IDs for the reports in the group above or below.

For a group of reports, a summarized confirmation to the group is also OK.

If there are any questions about a report, please leave a comment with the report ID or link, and I will reply the detailed path provided by our static analysis report.

## Undecreased refcnt due to the `return NULL` statement in macro `import_array`.

This issue also affects other projects.

https://github.com/numpy/numpy/blob/59aad3cf436691d447e43038e3402500f13cd817/numpy/core/src/umath/_operand_flag_tests.c#L60
https://github.com/numpy/numpy/blob/59aad3cf436691d447e43038e3402500f13cd817/numpy/core/src/umath/_struct_ufunc_tests.c#L126
https://github.com/numpy/numpy/blob/59aad3cf436691d447e43038e3402500f13cd817/numpy/core/src/umath/_umath_tests.c.src#L705
https://github.com/numpy/numpy/blob/eecd16210ffb487d4e862c71e86cc6f88f2e9aa2/numpy/linalg/umath_linalg.cpp#L4535
https://github.com/numpy/numpy/blob/b222eb66c79b8eccba39f46f020ed8303614a87f/numpy/fft/_pocketfft.c#L2374
https://github.com/numpy/numpy/blob/b222eb66c79b8eccba39f46f020ed8303614a87f/numpy/linalg/lapack_litemodule.c#L397

(79bbae ca50d3 281b63 7ce5a3 ab547b 9bedd0)

## On failure, return NULL directly without decreasing the refcnt.

New reference returned here is inherited from its argument, but not decreased when returned on line 379. (Take the true branch on line 370) (a7dae8)
https://github.com/numpy/numpy/blob/b222eb66c79b8eccba39f46f020ed8303614a87f/numpy/core/src/multiarray/calculation.c#L362

New reference returned here is inherited from its argument, but not decreased when returned on line 410. (Take the true branch on line 390) (fbd6d9)
https://github.com/numpy/numpy/blob/b222eb66c79b8eccba39f46f020ed8303614a87f/numpy/core/src/multiarray/calculation.c#L381

New reference returned here is not decreased when returned on line 435. (347302)
https://github.com/numpy/numpy/blob/b222eb66c79b8eccba39f46f020ed8303614a87f/numpy/core/src/multiarray/descriptor.c#L424

New reference returned here is not decreased when returned on line 2714. (Not decreased on normal branch either) (d3830d)
https://github.com/numpy/numpy/blob/b222eb66c79b8eccba39f46f020ed8303614a87f/numpy/core/src/multiarray/descriptor.c#L2707

Refcnt increased here is not decreased when returned on line 2756. (f9b533)
https://github.com/numpy/numpy/blob/b222eb66c79b8eccba39f46f020ed8303614a87f/numpy/core/src/multiarray/descriptor.c#L2716

New reference returned here is not decreased when returned on line 2827. (out-of-memory raised) (b4258c)
https://github.com/numpy/numpy/blob/b222eb66c79b8eccba39f46f020ed8303614a87f/numpy/core/src/multiarray/descriptor.c#L2810

New reference returned here is not decreased when returned on line 656. (42895d)
https://github.com/numpy/numpy/blob/b222eb66c79b8eccba39f46f020ed8303614a87f/numpy/core/src/multiarray/getset.c#L648

New reference returned here is not decreased when returned on line 2145. (out-of-memory raised) (d15060)
And not decreased on line 2123 in the latest version, runtime error raised.
https://github.com/numpy/numpy/blob/b222eb66c79b8eccba39f46f020ed8303614a87f/numpy/core/src/multiarray/methods.c#L2081

Return value of `PyModule_AddObject` is not checked, the 3rd argument will leak on failure. (c7a933 ee4e9c 0b9cee afba91 08c0c8)
https://github.com/numpy/numpy/blob/b222eb66c79b8eccba39f46f020ed8303614a87f/numpy/core/src/umath/umathmodule.c#L298
https://github.com/numpy/numpy/blob/b222eb66c79b8eccba39f46f020ed8303614a87f/numpy/core/src/umath/umathmodule.c#L299
https://github.com/numpy/numpy/blob/b222eb66c79b8eccba39f46f020ed8303614a87f/numpy/core/src/umath/umathmodule.c#L300
https://github.com/numpy/numpy/blob/b222eb66c79b8eccba39f46f020ed8303614a87f/numpy/core/src/umath/umathmodule.c#L301
https://github.com/numpy/numpy/blob/b222eb66c79b8eccba39f46f020ed8303614a87f/numpy/core/src/umath/umathmodule.c#L302

## Goto a label on a failure, but the new reference is not decreased in the error handling code.

* Assume the corresponding new reference object is not NULL.

New reference returned here is not decreased after jumping to a label. (2d7c3a 3e48a7)
https://github.com/numpy/numpy/blob/59aad3cf436691d447e43038e3402500f13cd817/numpy/core/src/umath/_rational_tests.c#L1134
https://github.com/numpy/numpy/blob/b222eb66c79b8eccba39f46f020ed8303614a87f/numpy/core/src/multiarray/descriptor.c#L538

New reference returned here is not decreased after `goto finish` if the parameter `kwnames` is NULL. (f5e33e)
https://github.com/numpy/numpy/blob/b222eb66c79b8eccba39f46f020ed8303614a87f/numpy/core/src/multiarray/arrayfunction_override.c#L417

**Comment by seberg** [comment]
Thanks, not sure how worrisome the import errors are but of course it is probably nice to fix.

The `calculation.c` issues might be best solved by just removing the whole `std` implementation and calling into the the normal (python based) code that `arr.std()` uses.

Anyway, thanks for the summary these all seem nicely actionable, for anyone who wants to work through and solve one or more.

**Comment by GermnGodoy** [comment]
Hi! I'd like to work on this issue.

I've checked all the files mentioned in the original issue. Most have already been fixed in previous commits, but I found that the problem still persists in these two files:

  - `numpy/_core/src/umath/_operand_flag_tests.c`
  - `numpy/_core/src/umath/_struct_ufunc_tests.c`

I've applied the fix (moving `import_array()` and `import_umath()` calls before `PyModule_Create()`) to both files and will submit a PR shortly.
