### ISSUE TITLE
BUG: tests crash on windows/msvc when built with meson

### ISSUE THREAD

**Issue by mattip** [numpy/numpy#23037]
I noticed this when trying out the meson build, which did not define -DNDEBUG. Removing that define should enable `assert()`s, I wonder if some assumption is off on windows.

**Comment by seberg** [comment]
I guess this wasn't with a Python 3.10 debug build (or newer), but just with NumPy debug flags?  In which case, it might have been fixed by the f2py fixup.

**Comment by mattip** [comment]
The crash is still happening even with the flag, in [test_deprecate_unparsable_data_file](https://github.com/mattip/numpy/actions/runs/4023884932/jobs/6915273666#step:13:1413):
```
..\build\Lib\site-packages\numpy\core\tests\test_deprecations.py::TestFromStringAndFileInvalidData::test_deprecate_unparsable_data_file[,invalid_data] 
Error: Process completed with exit code 1.

```

**Comment by seberg** [comment]
Hmmm, very unclear what could be the issue, I don't think there are any obvious asserts here and the test does text writing and more importantly reading.

Any chance of getting a stacktrace?

**Comment by mattip** [comment]
I can reproduce the failure locally. I will play with it a bit.

**Comment by mattip** [comment]
The process exits on an "invalid parameter error" when calling `_fopen` in [`npy_PyFile_Dup2`](https://github.com/numpy/numpy/blob/main/numpy/core/include/numpy/npy_3kcompat.h#L192). There is a mechanism for catching the invalid parameter error, in CPython  https://github.com/python/cpython/blob/main/Include/internal/pycore_fileutils.h#L264. The call should never fail since the `fd` is returned from `os.dup`.

**Comment by mattip** [comment]
I think somehow the meson build is picking up a different runtime library than the old build, so the integer file id is from a different c runtime. `depends.exe` is not very helpful in trying to determine which `_fdopen` is being used, but I have seen this before when mixing visual studio runtimes. So rather than doing more debugging I am trying to get the builds to emit the same link commands.

One difference between the meson link and the setup.py link is that meson adds in a whole list of extra windows libraries, where setup.py only links to the python import lib (via a `#pragma` in `pyconfig.h`) I looked for how I disable the list used in meson. I see the [documentation about compiler options](https://mesonbuild.com/Builtin-options.html#compiler-options) but cannot figure out where and how to "empty out" the `c_winlib` and `cpp_winlib` options. I tried this in the top level `meson.build` and it didn't work @eli-schwartz ideas?
```
  add_global_arguments('-Dc_winlibs=', language: ['c'])
  add_global_arguments('-Dcpp_winlibs=', language:['cpp'])
```

For completeness, here is the link log for `_multiarray_tests.cp39-win_amd64.pyd` in the two builds:

meson
```
"link"  /MACHINE:x64 /OUT:numpy/core/_multiarray_tests.cp39-win_amd64.pyd \
numpy/core/_multiarray_tests.cp39-win_amd64.pyd.p/meson-generated__multiarray_tests.c.obj \
numpy/core/_multiarray_tests.cp39-win_amd64.pyd.p/src_common_mem_overlap.c.obj \
numpy/core/_multiarray_tests.cp39-win_amd64.pyd.p/src_common_npy_argparse.c.obj \
numpy/core/_multiarray_tests.cp39-win_amd64.pyd.p/src_common_npy_hashtable.c.obj \
"/nologo" "/release" "/nologo" "/DEBUG" \
"/PDB:numpy\core\_multiarray_tests.cp39-win_amd64.pdb" \
"/DLL" "/IMPLIB:numpy\core\_multiarray_tests.cp39-win_amd64.lib" \
"C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\libs\python39.lib" \
"kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.lib" \ 
"oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib"
```

setup.py
```
INFO: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe \
/nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO \
/LIBPATH:d:\temp\cpython_39\libs \
/LIBPATH:C:\Program Files\WindowsApps \\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\libs \
/LIBPATH:C:\Users\matti\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0 \
/LIBPATH:d:\temp\cpython_39\PCbuild\amd64 \
/LIBPATH:build\temp.win-amd64-3.9 \
/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\x64 \
/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64 \
/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64 \
/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64 npymath.lib \
/EXPORT:PyInit__multiarray_tests \
build\temp.win-amd64-3.9\Release\build\src.win-amd64-3.9\numpy\core\src\multiarray\_multiarray_tests.obj \
build\temp.win-amd64-3.9\Release\numpy\core\src\common\mem_overlap.obj \
build\temp.win-amd64-3.9\Release\numpy\core\src\common\npy_argparse.obj \
build\temp.win-amd64-3.9\Release\numpy\core\src\common\npy_hashtable.obj \
/OUT:build\lib.win-amd64-3.9\numpy\core\_multiarray_tests.cp39-win_amd64.pyd  \
/IMPLIB:build\temp.win-amd64-3.9\Release\build\src.win-amd64-3.9\numpy\core\src\multiarray\_multiarray_tests.cp39-win_amd64.lib
```

**Comment by mattip** [comment]
Another option is that the `/MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO` argument is important, but let's leave that for a second step after removing the link libraries `"kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.lib" \ 
"oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib"`

**Comment by eli-schwartz** [comment]
> I tried this in the top level `meson.build` and it didn't work @eli-schwartz ideas?

Global arguments are for the compiler, and -D happens to also be a valid compiler flag. :)

(Well, translated to /D...)

You're looking for "default options" (for the meson configuration), see the `project()` function.

**Comment by mattip** [comment]
> You're looking for "default options" (for the meson configuration), see the project() function.

Sorry, could you expand a bit? Which `project()` function? Is there an example somewhere of how to do this?

**Comment by mattip** [comment]
The documentation for compiler options says 
> The following options are available. They can be set by passing `-Doption=value` to meson but doesn't show __how__ to do that.

**Comment by mattip** [comment]
Ahh, I got it: in the top-level `meson.build`

**Comment by mattip** [comment]
Adding `c_winlib=`, `cpp_winlib=` to the `default_settings` did not help, the libraries are still used:
```
project(
  'NumPy',
  'c', 'cpp', 'cython',
  # Note that the git commit hash cannot be added dynamically here
  # It is dynamically added upon import by versioneer
  # See `numpy/__init__.py`
  version: '1.24.0.dev0',
  license: 'BSD-3',
  meson_version: '>= 0.64.0',
  default_options: [
    'buildtype=debugoptimized',
    'c_std=c99',
    'cpp_std=c++14',
    'blas=openblas',
    'lapack=openblas',
    'pkgconfig.relocatable=true',
    'c_winlib=',
    'cpp_winlib=',
  ],
)

```

**Comment by mattip** [comment]
ahh, wait, the build is `'buildtype=debugoptimized',`, that is going to link to the wrong runtime. Setting that to `release` gets me past the crash. Grr. I wonder why setting that did not define `_DEBUG` which would have [triggered linking to the debug python runtime](https://github.com/python/cpython/blob/main/PC/pyconfig.h#L289).

OK, tests now pass. How can I toggle that setting when `is_windows` and set it to `release` only on windows?

**Comment by eli-schwartz** [comment]
Maybe it makes more sense to just set the CRT?

- `-Db_vscrt=md` passes `/MD`

- `-Db_vscrt=mdd` passes `/MDd`


The default value of b_vscrt is "from_buildtype" and a debug buildtype thus sets the CRT to "mdd".

**Comment by eli-schwartz** [comment]
You could also check the value of `get_option('b_vscrt')` and pass additional defines manually. I could also check the feasibility of doing this automatically in Meson.

**Comment by mattip** [comment]
Passing `/MDd` would [automatically set `_DEBUG`](https://learn.microsoft.com/en-us/cpp/c-runtime-library/debug?view=msvc-170), and I did not see `/MDd` in the build logs.  Somehow something else is happening with the `buildtype`. 

I don't know enough about meson to parse "just set the CRT". Where would I do this, how do I see an example of such a setting? My meson foo is practically zero, and there are multiple places to modify settings: each directory had a `meson.build` and there are different commands to set values at each level.

**Comment by mattip** [comment]
I see that I was using the command from the github action `meson setup build --prefix=$PWD\build --buildtype plain --vsenv`. I think this was suggested when I was having problems with getting meson to ignore the various gcc compilers. What does the `--buildtype plain` do? Could that be problematic?

**Comment by mattip** [comment]
Using `--buildtype release` got me further in the [github action run](https://github.com/mattip/numpy/actions/runs/4075714364/jobs/7022481531#step:13:24290). Now I see a segfault in `test_random`: `Windows fatal exception: code 0xc0000374` which is `STATUS_HEAP_CORRUPTION`

**Comment by mattip** [comment]
I am now using this to setup meson. For some reason the `-Ddebug=false` was important in order to link to the correct runtime.
```
meson setup build --prefix=$PWD\build-install -Ddebug=false --optimization 2 --vsenv
```

**Comment by mattip** [comment]
Closing, the build is no longer crashing.

**Comment by rgommers** [comment]
From https://github.com/numpy/numpy/issues/23122#issuecomment-1420707400, may explain what happened:

Are you compiling with `-DNDEBUG` ? I *think* this symbol is brought by `assert` and as we compile without linking to the standard lib, this symbol would indeed be undefined. To avoid the situation, without linking with the standard library, we would need to provide our own assert.
