### ISSUE TITLE
How we want to link with MKL, and a missing symbol issue

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy#24824]
In the process of adding a CI job using MKL, I came across a quite annoying linking issue which many people before me have stumbled on, and few managed to solve. The CI job is simple, it basically does:
```
# Install build and test requirements - MKL (2020.4) from Debian
pip install -r build_requirements.txt
pip install pytest pytest-xdist hypothesis typing_extensions
sudo apt-get install intel-mkl pkg-config

# Build against MKL with the options we want
spin build -- -Dblas=mkl-dynamic-lp64-seq -Dlapack=mkl-dynamic-lp64-seq

# Run tests
spin test -- numpy/linalg
```

The build worked straight away, but the tests crash with:
```
INTEL MKL ERROR: /lib/x86_64-linux-gnu/libmkl_avx512.so: undefined symbol: mkl_sparse_optimize_bsr_trsm_i8.
Intel MKL FATAL ERROR: Cannot load libmkl_avx512.so or libmkl_def.so.
```

That particular undefined symbol issue can be found reported in many places, e.g. 
- https://github.com/ContinuumIO/anaconda-issues/issues/698
- https://github.com/pykaldi/pykaldi/issues/143
- https://github.com/facebookresearch/faiss/issues/2021
- https://stackoverflow.com/questions/54694862/intel-mkl-and-jni-how-to-add-a-shared-library-that-ld-searches-symbols-from
- https://github.com/AnacondaRecipes/numpy-feedstock/pull/5

The last link above explains the problem best: MKL is split across multiple shared libraries, and they need to be `dlopen`-ed with `RTLD_GLOBAL`. Python extension modules use `RTLD_LOCAL`, and hence symbols go missing.

Preloading the relevant libraries works around the problem in the CI job and then all test pass:
```
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libmkl_core.so:/usr/lib/x86_64-linux-gnu/libmkl_sequential.so
```
That's not a solution of course. I found [one thread on the Intel forum](https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/Setting-MPI-for-MKL/m-p/1406183#M33479) that hints at some (or all?) of these issues being solved in MKL 2023.0. @oleksandr-pavlyk do you know if that is indeed the case?

* * *

When building with MKL in a `numpy.distutils` based build we didn't encounter this issue, because we link with `-lmkl_rt` to use the [Single Dynamic Library](https://www.intel.com/content/www/us/en/docs/onemkl/developer-guide-linux/2023-0/using-the-single-dynamic-library.html) (SDL). That was fine for a long time, but defaulting to LP64 and Intel OpenMP and selecting anything else [with environment variables](https://www.intel.com/content/www/us/en/docs/onemkl/developer-guide-linux/2023-0/dynamic-select-the-interface-and-threading-layer.html) is not really a great fit anymore now that we have full ILP64 support and defaulting to that in our own wheels.

A second issue is that the pkg-config files Intel ships support linking against the separate libraries, not the SDL. Only in 2023.0 did they start shipping `mkl-sdl.pc`. Not a showstopper - for older MKL versions that could be worked around by querying for other libraries and then using the include paths from those with `-lmkl_rt` - but not ideal either.

I had this interface in mind for `pip install numpy`, using the ["layered model'](https://www.intel.com/content/www/us/en/docs/onemkl/developer-guide-linux/2023-0/layered-model-concept.html#GUID-45FE75D8-E55C-44A4-BE8F-9CC0F1805F46):
- the default is `-Dblas=auto, -Dlapack=auto`, and when MKL is found it would use `mkl-dynamic-lp64-seq`
- using  `-Dblas=mkl -Dlapack=mkl` would do the same
- using `-Dblas=mkl -Dlapack=mkl -Duse-ilp64` would use `mkl-dynamic-ilp64-seq`
- any other MKL variant can be selected directly by using the name of the relevant pkg-config file (e.g. `-Dblas=mkl-dynamic-ilp64-iomp`)

The way this would look in `numpy/meson.build` would be pretty simple, mainly parsing CLI flags and then effectively calling something like:
```meson
blas_dep = dependency('mkl',
  version: '>=2021.1.0',
  modules: [
    interface: 'lp64',   # options are 'lp64' or 'ilp64'
    threading: 'seq',    # options are 'seq' or 'omp'
    library: 'dynamic',  # options are 'dynamic' or 'static'
  ]
)
```
with the knowledge of pkg-config file names, compile/link flags, env vars like MKLROOT etc. living in Meson.

I think we have several options:
1. In case it's indeed fixed in MKL 2023.0, use that as a minimum version and stay with the above plan, or fall back to `-lmkl_rt` for older versions
2. Forget about a nicer interface and just blindly link `-lmkl_rt` like `numpy.distutils` did
3. Work around the problem by a patch a la https://github.com/AnacondaRecipes/numpy-feedstock/pull/5

**Comment by mattip** [comment]
Since the source of the problem is in MKL, I think forcing a minimum version that works with meson/numpy makes sense (assuming they did indeed fix it), so (1). As a fall back, it seems like (3) would be better than (2), since we could rip it out once MKL fixes the problem.

> with the knowledge of pkg-config file names, compile/link flags, env vars like MKLROOT etc. living in Meson.

I am a little concerned about meson itself growing a whole bunch of BLAS options. Shouldn't there be a plugin system for meson or another way to add functionality that would be a more modular home for things like BLAS/LAPACK options and our patches for SIMD detection/compilation, something like meson-python?

**Comment by mattip** [comment]
meson has a [`pkg_config_path` build](https://mesonbuild.com/Builtin-options.html#core-options) setting, so much of this complexity could be pushed into a mkl.pc file  as compile and link flags and the file path passed in to meson. There is even a [`Pkgconfig` module](https://mesonbuild.com/Pkgconfig-module.html) to generate pkgconfig files.

**Comment by rgommers** [comment]
Thanks Matti, that's useful feedback. I'll figure out if it's indeed fixed, or hopefully @oleksandr-pavlyk will know all the details here already.

> Shouldn't there be a plugin system for meson or another way to add functionality

No there isn't, and that's by design - it's one of the things I like actually. Plugins just lead to everyone keeping their own tweaks around and things being a complete mess like with distutils `build_ext` patching. The point is to have people upstream things and get them right.

Linking with BLAS libraries is a similar level of complexity as linking Python interpreters - you want that in a single place.

> so much of this complexity could be pushed into a mkl.pc file as compile and link flags and the file path passed in to meson

MKL ships `.pc` files, and I'll be using those. There's a "system" dependency as a fallback, for when the .pc files are missing - and that's the only place where things should grow more complex.

**Comment by oleksandr-pavlyk** [comment]
@rgommers I have verified in https://github.com/oleksandr-pavlyk/use-mkl-in-meson-example that the problem you encountered is resolved in `conda-forge::mkl-devel=2023.2=ha770c72_49502`. The specific build number is to pick up the fix for misplaced `pkconfig/*.pc` files during repackaging.

The pkgconfig files in `intel::mkl-devel` package have hard paths specific to oneAPI installation path, rather than Python prefix path. It, unfortunately, remains broken.

**Comment by rgommers** [comment]
@oleksandr-pavlyk thanks for the .pc file checks/fixes. This question is not about that though, it's about the need for `RTLD_GLOBAL`, which doesn't work with Python extensions - the thing you worked around in https://github.com/AnacondaRecipes/numpy-feedstock/pull/5. Is that fixed now, or still the same as it always was?

**Comment by oleksandr-pavlyk** [comment]
@rgommers Maybe I misunderstood the problem but I took that the `./toy_use_mkl` example correctly executing as meaning that the issue has been fixed.

I am also able to use `ctypes` to load `mkl_rt` and successfully look up a symbol in there:

```
(meson_build_example) opavlyk@opavlyk-mobl:~/repos/meson-build/build$ python
Python 3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:34:09) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes
>>> lib = ctypes.cdll.LoadLibrary("libmkl_rt.so")
>>> lib.cblas_ddot
<_FuncPtr object at 0x7f83d01f86d0>
```

**Comment by rgommers** [comment]
Ah okay

> Maybe I misunderstood the problem but I took that the `./toy_use_mkl` example correctly executing as meaning that the issue has been fixed.

Ah okay, yes - I missed that. That example uses `mkldep = dependency('mkl-dynamic-ilp64-iomp')`, and that was still broken in Debian (which packages MKL `2020.4` as the most recent version). So I agree, this must be fixed now.

**Comment by rgommers** [comment]
> I am also able to use `ctypes` to load `mkl_rt` and successfully look up a symbol in there:

`mkl_rt.so` was never the problem, because that's a single library with all symbols. The problem was with the layered model, where you link multiple libraries:
```
$ pkg-config --libs mkl-dynamic-lp64-seq
-L/home/rgommers/mambaforge/envs/mkl-2023/lib -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl
```

I'm not able to open any of those linked libraries with `ctypes` (that always ends with missing symbols), and none of them depend on `mkl_rt`. So the design of that is a little tricky.

**Comment by rgommers** [comment]
> So the short answer to your original question is that the issues is fixed in MKL 2023. In addition to the testing I also obtain confirmation from the MKL team that the issue has indeed been fixed in 2023 release.

Great, thanks again! Then I think we'll require MKL 2023 as the minimum version for now and call it good.
