### ISSUE TITLE
BUG: Cannot convert masked array of python datetimes to datetime64 after changing fill value

### ISSUE THREAD

**Issue by ArthurGW** [numpy/numpy#26899]
### Describe the issue:

When creating a masked array with object dtype, with the init argument `fill_value=datetime.datetime.max` (for example), then later changing the fill value to a different datetime value, calling `marray.astype('datetime64[...])` results in an error converting the fill value to the new dtype. (This is also the case if you re-set exactly the same fill value.)

Internally, the fill value you pass in ends up wrapped in two layers of numpy.array, i.e. `broken._fill_value`  == `array(array(datetime.datetime(1, 1, 1, 0, 0), dtype=object), dtype=object)`. This object cannot be converted.

I suspect this would happen for other object arrays, since the code that wraps the fill value in an array to make it a numpy scalar doesn't do anything specific with datetimes.

The error message you get is a bit misleading, "TypeError: Cannot convert fill_value 0001-01-01 00:00:00 to dtype datetime64[s]", because it doesn't show that it's actually wrapped in arrays. Took me a while to puzzle over that one!

There is a workaround: instead of _changing_ the fill value on the MA, create a new MA: `numpy.ma.array(broken, fill_value=datetime.datetime.min).astype('datetime64[...])` works. I don't know if this results in any inefficient copying though.

### Reproduce the code example:

```python
import numpy as np

# This array converts fine
works = numpy.ma.array([datetime.datetime.now(), None],
                       mask=[False, True], 
                       fill_value=datetime.datetime.min)

works.fill_value  # output: datetime.datetime(1, 1, 1, 0, 0)
works._fill_value  # output: array(datetime.datetime(1, 1, 1, 0, 0), dtype=object)
works.astype('datetime64[s]')  # works

# This doesn't after setting `broken.fill_value`
broken = numpy.ma.array([datetime.datetime.now(), None],
                        mask=[False, True],
                        fill_value=datetime.datetime.max)

broken.fill_value = datetime.datetime.min  # This breaks things
broken.fill_value  # output: array(datetime.datetime(1, 1, 1, 0, 0), dtype=object) - note the extra array/scalar wrapper around the object
broken._fill_value  # output: array(array(datetime.datetime(1, 1, 1, 0, 0), dtype=object), dtype=object) - note the double array wrapper
broken.astype('datetime64[s]')  # fails
```

### Error message:

```shell
Traceback (most recent call last):
  File "...\lib\site-packages\numpy\ma\core.py", line 462, in _check_fill_value
    fill_value = np.array(fill_value, copy=False, dtype=ndtype)
ValueError: Could not convert object to NumPy datetime

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "...\lib\site-packages\numpy\ma\core.py", line 3062, in __array_finalize__
    self._fill_value = _check_fill_value(self._fill_value, self.dtype)
  File "...\lib\site-packages\numpy\ma\core.py", line 468, in _check_fill_value
    raise TypeError(err_msg % (fill_value, ndtype)) from e
TypeError: Cannot convert fill_value 0001-01-01 00:00:00 to dtype datetime64[s]
```

### Python and NumPy Versions:

1.21.6
3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]

### Runtime Environment:

<numpy version 1.21>

### Context for the issue:

We often use object arrays of python datetime.date(/time) instances

**Comment by seberg** [comment]
The code succeeds for me on NumPy 1.26.4 and current main, so I suspect something got fixed and you will simply have to update.  I don't know what or when, though.

Could you confirm it's fixed (or make sure the sample reproduces the failure).

**Comment by ArthurGW** [comment]
@seberg I'll have a check today, thanks for looking at it

**Comment by ArthurGW** [comment]
@seberg Ah this is interesting. These two lines still come out weird, same output as before:
```
broken.fill_value  # output: array(datetime.datetime(1, 1, 1, 0, 0), dtype=object)
broken._fill_value  # output: array(array(datetime.datetime(1, 1, 1, 0, 0), dtype=object), dtype=object)
```

But now this call succeeds during `__array_finalize__` (in `_check_fill_value`), when it previously failed (I filled in the actual values used in the call):

`fill_value = np.array(np.array(np.array(datetime.datetime(1, 1, 1, 0, 0), dtype=object), dtype=object), copy=False, dtype=dtype('<M8[s]'))`

So it looks like the underlying bug in MA code is still there, but it doesn't cause any visible problems any more. Not sure what numpy's policy is on fixing that sort of issue, I'll leave it up to you!

**Comment by fengluoqiuwu** [comment]
It seems that the bug has fixed in the development version. The output I received is as follows:

```python
works.fill_value=datetime.datetime(1, 1, 1, 0, 0)
works._fill_value=array(datetime.datetime(1, 1, 1, 0, 0), dtype=object)
broken.fill_value=array(datetime.datetime(1, 1, 1, 0, 0), dtype=object)
broken._fill_value=array(array(datetime.datetime(1, 1, 1, 0, 0), dtype=object), dtype=object)
broken.fill_value=array(datetime.datetime(1, 1, 1, 0, 0), dtype=object)
broken.astype('datetime64[s]')=masked_array(data=[datetime.datetime(2024, 10, 20, 20, 19, 24), --],
             mask=[False,  True],
       fill_value=0001-01-01T00:00:00,
            dtype='datetime64[s]')

```
Is this the expected behavior?

**Comment by seberg** [comment]
@fengluoqiuwu I think it is somewhat fixed.  But the double wrapping is still wrong.  When assigning a `fill_value` to an object dtype, it seems like we wrap it into an (additional) array.  But what we should be getting is the same result as: `self._fill_value = np.empty((), dtype=object); self._fill_value[()] = fill_value`.

(Although things are tricky if `fill_value` is already a 0-D array, since in that case, the intention is presumably to unwrap that array, and the above code would not do that.)

I am not sure where that second nesting comes from right away.  Maybe the `recursive_set_fill_value`?

**Comment by fengluoqiuwu** [comment]
@seberg Oh, sorry for misunderstanding your meaning. However, there are two basic issues causing this problem, and it seems to stem from `ndarray`, not specifically from the masked array.

The first issue relates to `dtype`. It appears that `ndarray` does not recognize `datetime` and treats it as `object` unless specified explicitly by parameters. For example:

```python
>>> import numpy as np
>>> import datetime

>>> print(f"{np.array(1)=}")                     # works with int
np.array(1)=array(1)
>>> print(f"{np.array(datetime.datetime.min)=}")  # fails with datetime
np.array(datetime.datetime.min)=array(datetime.datetime(1, 1, 1, 0, 0), dtype=object)  
>>> print(f"{np.array(datetime.datetime.min,dtype=np.datetime64)=}")   # works if I give it dtype
np.array(datetime.datetime.min,dtype=np.datetime64)=array('0001-01-01T00:00:00.000000', dtype='datetime64[us]')
```

The second issue pertains to scalar access, which behaves unexpectedly with objects that are not part of NumPy (or perhaps there are some misunderstandings on my part):

```python
>>> fill_value = np.array(1)
>>> fill_value[()] = np.array(1)
>>> fill_value                                           # works with int type
array(1)

>>> class A:
>>>     def __init__(self):
>>>         self.a = 0
>>> fill_value = np.array(A())
>>> fill_value[()] = np.array(A())
>>> fill_value                                           # fails with any object type
array(array(<__main__.A object at 0x00000132D5E4A0C0>, dtype=object), dtype=object)
```
I haven't learned enough about C code yet, so I'm unable to address these issues myself. I hope someone else can take a look and help with a fix.

**Comment by ngoldbaum** [comment]
The original issue has been fixed. Please open a new one with a clear reproducer for the remaining issues under discussion here if anyone still cares about these issues.
