### ISSUE TITLE
Make `eig/eigvals` always return complex eigenvalues

### ISSUE THREAD

**Issue by ev-br** [numpy/numpy#29000]
For a real-valued input, NumPy's eigenvalue routines currently may return either real or complex eigenvalues: both `eig` and `eigvals` check for imaginary parts being exactly zero, and downcast the output if they are [1].

Other array libraries skip this handholding and always return complex eigenvalues. For instance,

In [10]: torch.linalg.eig(torch.arange(4).reshape(2, 2)*1.0).eigenvalues
Out[10]: tensor([-0.5616+0.j,  3.5616+0.j])

A recent array-api discussion [2], had a question if NumPy would consider changing this value-dependent behavior and always return a complex array for eigenvalues?

What is the downstream effect. Were we starting from scratch, I'd expect that doing `real_if_close` is not that taxing for a user---and in fact in the vast majority of use cases it's just not needed.

Since we're not starting from scratch, and to roughly assess the blast radius, I applied the following patch (hidden under the fold), and ran tests for scipy, scikit-learn and scikit-image. 

Here's the summary: 

**scipy**:

SciPy: 4 failures in scipy.signal, all look trivial to fix

FAILED signal/tests/test_dltisys.py::TestStateSpaceDisc::test_properties - AssertionError: dtypes do not match.
FAILED signal/tests/test_dltisys.py::TestTransferFunction::test_properties - AssertionError: dtypes do not match.
FAILED signal/tests/test_ltisys.py::TestStateSpace::test_properties - AssertionError: dtypes do not match.
FAILED signal/tests/test_ltisys.py::TestTransferFunction::test_properties - AssertionError: dtypes do not match.

**scikit-learn**:

all tests pass

**scikit-image**:

FAILED measure/tests/test_fit.py::test_ellipse_model_estimate - TypeError: unsupported operand type(s) for %=: 'numpy.complex128' and 'float'
FAILED measure/tests/test_fit.py::test_ellipse_parameter_stability - TypeError: unsupported operand type(s) for %=: 'numpy.complex128' and 'float'
FAILED measure/tests/test_fit.py::test_ellipse_model_estimate_from_data - TypeError: unsupported operand type(s) for %=: 'numpy.complex128' and 'float'
FAILED measure/tests/test_fit.py::test_ellipse_model_estimate_from_far_shifted_data - TypeError: unsupported operand type(s) for %=: 'numpy.complex128' and 'float'

[1] https://github.com/numpy/numpy/blob/v2.1.0/numpy/linalg/_linalg.py#L1226
[2] https://github.com/data-apis/array-api/issues/935#issuecomment-2885643761

<details>

```diff
$ git diff
diff --git a/numpy/linalg/_linalg.py b/numpy/linalg/_linalg.py
index d7850c4a02..7b44f73588 100644
--- a/numpy/linalg/_linalg.py
+++ b/numpy/linalg/_linalg.py
@@ -1269,14 +1269,15 @@ def eigvals(a):
                   under='ignore'):
         w = _umath_linalg.eigvals(a, signature=signature)
 
-    if not isComplexType(t):
-        if all(w.imag == 0):
-            w = w.real
-            result_t = _realType(result_t)
-        else:
-            result_t = _complexType(result_t)
 
+    result_t = _complexType(result_t)
    return w.astype(result_t, copy=False)
 
 
 def _eigvalsh_dispatcher(a, UPLO=None):
@@ -1522,13 +1523,14 @@ def eig(a):
                   under='ignore'):
         w, vt = _umath_linalg.eig(a, signature=signature)
 
-    if not isComplexType(t) and all(w.imag == 0.0):
-        w = w.real
-        vt = vt.real
-        result_t = _realType(result_t)
-    else:
-        result_t = _complexType(result_t)
 
+    result_t = _complexType(result_t)
     vt = vt.astype(result_t, copy=False)
     return EigResult(w.astype(result_t, copy=False), wrap(vt))
```

</details>

**Comment by ngoldbaum** [comment]
I think we'd have to come up with a new function that has a different return type. A few versions later, we could deprecate `eig` and `eigvals` and point people to the new function.

We can't just change the return types though IMO because then it becomes annoying to simultaneously support several NumPy versions. We also can't generate new deprecation warnings for `eig` and `eigvals` without a replacement, because then there's nothing people can do to fix it, particularly when users trigger this in libraries.

**Comment by ilayn** [comment]
>  real_if_close is not that taxing for a user---and in fact in the vast majority of use cases it's just not needed.

Quite the other way around. I think this is an intrusive change and make things really complicated for linear algebra code. Because it will require checking the imaginary part every time you have an eigvals code. I would argue that this is a change not due to usability improvement but to regularize type system that I don't find sufficiently strong reason about. 

I am aware of the array api work, but this should not come at the expense of giving up the convenience of a dynamic language. 

> eigvals(x, /) should return an array of eigenvalues in an unspecified order;

This one is also very problematic. Tons of code relies on this behavior and the behavior is pretty much written in stone at this point. Instead of changing established conventions, the other libraries should look for ways to mimic this behavior.

**Comment by ev-br** [comment]
> I am aware of the array api work, but this should not come at the expense of giving up the convenience of a dynamic language.

Array API discussion is a for context only, and is not a motivation for this request. So let's not tangle this in. [1]


> it will require checking the imaginary part every time you have an eigvals code. 

Will it really? To me, it's a pure math thing: eigenvalues of a real matrix are complex-valued. They can --- by accident --- have zero imaginary parts. These zero imaginary parts can --- again, by accident --- become identically zero in floating point, but in general one needs some tolerance to decide if `.imag` is zero or not. And that tolerance is problem-dependent. Just like a matrix rank, which is ill-defined in inexact arithmetic.

And I stand by the OP statement that  the very need to decide if eigenvalues are or are not exactly on the real axis of the complex plane is rare.

That a bunch of code has possibly already been written to expect handholding from numpy is a separate matter. A small experiment running scipy and scikit-{learn,image} test suites above seems to hint that the amount of such code is not that large. We can of course question how representative that exercise is, but by all means, if we reject the change because of potential backwards compatibility concerns, let's be clear about it and not mix up any other reasons.


[1] For the record (and I'm already on record elsewhere): IMO the array API movement is in itself not a reason to change anything, full stop. It can serve as a motivation, yes, but any change initiated by array API should be weighted on its own merits, not only consistency between array backends.

**Comment by ngoldbaum** [comment]
IMO this is worth doing. Having consistent output types is also better for JITs like numba or AoT compilers.

Maybe it could be done by adding a new keyword argument that forces imaginary output? In a future version we could deprecate `cast_to_float=True` to force people to update their code if we detect a case where a cast happens by generating a warning. Later, we'd update the default for the keyword and library authors can delete the kwarg. That would allow the array API compat to work eventually.

Either way we need a story for library authors that ideally allows them to avoid adding code that depends on NumPy version in all cases. Library authors that want to jump the gun and write version-dependent code can do so, but we shouldn't generate any new deprecation warnings that *force* library authors to have version-dependent code.

**Comment by ilayn** [comment]
> A recent array-api discussion [2], had a question if NumPy would consider changing this value-dependent behavior and always return a complex array for eigenvalues?

I am assuming this is the reason but otherwise what's the reason to change it? 

 > That a bunch of code has possibly already been written to expect handholding from numpy is a separate matter. 

Yes and that's how Python took off with hand-holding everywhere meaning providing a convenient interface. Otherwise we would be still coding in braces or `implicit none`s. So trying to reshape a dynamic language to a typed thing should not be the originator of lots of changes. I can also make the counter argument if you need type safety then you are coding in the wrong place. But that won't solve the discussion at hand so let's not get in there. 

The type safe way of doing this is the classical return-two-arrays in LAPACK or other compiled sources that you get one array `wr` for real parts and `wi` for imaginary parts. It is as unnecessary as writing `if any(eigs.imag() != 0.0): ...` everywhere but not the end of the world. Probably, we can make it work but then again what is the reasoning. Did we get complaints, is this hindering anything if not array api? 

I also want to be clear about our intentions and not make up reasons to avoid the fact that this is coming from array api. So it should go both ways. 



Independent from the dtype, the eigenvalue ordering, that's a major battle altogether.

**Comment by ev-br** [comment]
> I am assuming this is the reason but otherwise what's the reason to change it?

The array API discussion linked above is a context where this issue originates, yes. 

NumPy uses one convention and PyTorch uses a different convention. FTR, I'm suggesting that CuPy (which is the original motivation for the whole story) follows pytorch not numpy in https://github.com/cupy/cupy/pull/8980. 

> that's how Python took off with hand-holding everywhere

That might be, but I'd argue that _everywhere_ should be _where reasonable_, as with time we've seen both kinds of interfaces.

So for me, the reason is just the math.

With my comp phys / applied maths hat on, every time I see `fp_value == 0`, I <s>freak out</s> start thinking whether it should have a finite tolerance instead.
Which begs the question, does LAPACK really guarantee exactly zero imaginary parts for real eigenvalues? 

Also, what are the applications/use cases where returning complex eigenvalues with zero imaginary parts breaks something? I don't mean existing implementations (where the scipy/scikit-learn/scikit-image test suites seem to hint at an answer), I mean computational problems. I can only think of `np.roots`.

> I also want to be clear about our intentions and not make up reasons to avoid the fact that this is coming from array api.

Sure, this is in the OP :-).

>Maybe it could be done by adding a new keyword argument that forces imaginary output? In a future version we could deprecate cast_to_float=True to force people to update their code if we detect a case where a cast happens by generating a warning. Later, we'd update the default for the keyword and library authors can delete the kwarg. That would allow the array API compat to work eventually.

> Either way we need a story for library authors that ideally allows them to avoid adding code that depends on NumPy version in all cases. Library authors that want to jump the gun and write version-dependent code can do so, but we shouldn't generate any new deprecation warnings that force library authors to have version-dependent code.

With a downstream library maintainer hat on, I don't see how a keyword helps. Downstream, we'll need to first add a keyword (with a version check), then silence the deprecation warnings, then remove it. It's way simpler to just add an `if np.__version__ < 2.X: ...` once.

**Comment by ngoldbaum** [comment]
> With a downstream library maintainer hat on, I don't see how a keyword helps. Downstream, we'll need to first add a keyword (with a version check), then silence the deprecation warnings, then remove it. It's way simpler to just add an if np.__version__ < 2.X: ... once.

SciPy is a very engaged downstream. I'm thinking of people with less resources, who would prefer to have a one-liner they could use, or even retain their old code - which after all isn't broken.

Another advantage of the keyword argument approach is that we can make it so the deprecation warning only triggers if you don't specify the keyword. Anyone who wants to make their code always handle imaginaries can choose to make their code depend on numpy version and use the keyword instead of casting if it's available. Anyone who wants to keep their code as-is just explicitly sets e.g. `cast_to_float=True` and leaves their code alone. Anyone who doesn't care about fixing deprecations also doesn't have to do anything.

In a few numpy versions we expire the deprecation. At that point the lazy people who don't care about deprecations can just set the keyword or do the migration to always handle imaginaries. Either way it's not much work and they don't need to figure out the correct way to make their code depend on numpy version.

**Comment by seberg** [comment]
This was brought up, and I am honestly wondering if it isn't better to just flip it.  And if that means writing a short NEP because we skip deprecation... Then so be it.  And even if we wait until we can reasonably do the next major release (which can be a small major release), that might not be so bad?

I suppose I can be convinced that deprecation is also fine because this maybe almost never happens, but it seems very tedious to change a kwarg twice (you got to drop it again) for something you probaly don't care about.
(That is, I am wondering what's the chance that returning complex actually breaks follow-up code?)

**Comment by leofang** [comment]
Returning complex values is the right move. Instead of viewing this discussion as introducing a breaking change, I argue this is a NumPy bug (value-dependent casting) that should have been fixed by NumPy 2.0. It is not too late 🙂

**Comment by ilayn** [comment]
I still don't think this is the right move. Especially the argument to have it so that the return type is consistent is quite weak and unnecessarily making things complex valued where it is uncalled for. The reasoning should be algorithmic and not some type consistency in my opinion. Python is not a typed language after all.

**Comment by ev-br** [comment]
1. The failure in the scikit-image test suite (in the OP) is basically https://github.com/scikit-image/scikit-image/issues?q=is%3Aissue%20state%3Aopen%20eig --- there are several issues with eigenvalues becoming complex _sometimes_. The change will make them always complex. The failure is basically this:

```
>>> np.complex128(3) % np.pi
Traceback (most recent call last):
TypeError: unsupported operand type(s) for %: 'numpy.complex128' and 'float'
```

2. I scrolled through several pages of the GH code search for `np.linalg.eig(`, to have a feeling for a long tail which might feel the change of the dtype. Hard to get quantitative data, but the feeling is that it's very common to see `np.linalg.eig(covariance_matrix)`. The fix is of course to use `eigh` instead of `eig`.

**Comment by mattip** [comment]
> `unsupported operand type(s) for %: 'numpy.complex128' and 'float'`

Rather then change eigenvalues, perhaps we should make this work.

Edit: `complex % float` is different than `complex % complex`

**Comment by seberg** [comment]
> Hard to get quantitative data, but the feeling is that it's very common to see

At least for those specific users a warning is actually nicer, since they are informed that there they can improve their code.

Can we find the solution for `scikit-learn`!?  Because if that is complicated, we might want a kwarg or new function or so for that? And if that is the case, that might just inform the transition path as well maybe a kwarg or something else...[^1]

The question is how often you don't care about the return type and are OK with it being complex?
If that is common enough, a warning would be very disruptive with, honestly, relatively little gain. And unless we have a nice idea for a good transition, I still think it might be easier to possibly prepare now but actually just rip the band-aid off at some future point.
(But my opinion has always been that we should make "major" but not very disruptive releases every few year; as a rough guideline not earlier than dropping 3.12 or ~3-4 years after 2.0, even if I don't really want to do a recompile release).


[^1]: And yes, I have heard the argument that kwargs that change return types are bad.  I am until now  unconvinced by this as a principle/guideline. The actual guideline is to not have *value dependent* return types...
But `method="variant"` isn't value dependent at all!  It is *type* dependent as long as you don't forget that `Literal["variant"]` is very much a type and not a value. (Yes, the runtime doesn't enforce the "literal" part, but so be it. Type checkers will and literally nobody will use a non-literal anyway. And maybe I am missing it, but I don't see why JITs should have any difficulty dealing with literals -- I am sure they e.g. do things like transforming `x**2` to `square(x)`.)

**Comment by ev-br** [comment]
The `scikit-image` solution is two-fold I believe. 

What is the problem. The failure is in this line [1]: 

```
phi %= np.pi 
```

with `phi` is a numpy scalar computed from outputs of `np.eig`. The remainder assumes that `phi` is real and emits a ComplexWarning otherwise. Currently, this line _sometimes_ fails: [2]. Note that Stefan asked for a reproducer [3], in 2023.


[1] https://github.com/scikit-image/scikit-image/blob/959c3b8500cb212dabf3e0ed594a8169d44a113a/src/skimage/measure/fit.py#L905
[2] https://github.com/scikit-image/scikit-image/issues/7013
[3] https://github.com/scikit-image/scikit-image/issues/7013#issuecomment-1583203321

So AFAIU,
- scikit-image code assumes that eigenvalues are real;
- this sometimes breaks (because actually no, they are not always real)
- scikit-image considers this a bug


Therefore, the fix is two-fold:

Step 1: replace

```
eig_vals, eig_vecs = np.linalg.eig(M)
```

with

```
eig_vals, eig_vecs = np.linalg.eig(M)
if eig_vals.imag != 0:
      # emit a ComplexWarning or raise

eig_vals = eig_vals.real
eig_vecs = eig_vecs.real
```

Step 2: once there is a reproducer, scikit-image can investigate the fix.

**Comment by seberg** [comment]
Aha?  I thought it sometimes fails due to funky lapack/blas implementations.  And short of them having terrible bugs that we should maybe not work around, I would assume that is minor numerical inaccuracy.
But if it is numerical inaccuracy, if scikit-image doesn't just want to remove the `== 0` sanity check then they would need something smarter that finds clear violations but doesn't barf on numerical inaccuracies?

**Comment by ilayn** [comment]
Also the Schur complement needs to be written with `linalg.solve` and not `linalg.inv` s to improve the accuracy. In the degenerate cases, LAPACK will give eigenvalues with nonzero imaginary parts due to numerical noise. 

https://github.com/scikit-image/scikit-image/blob/959c3b8500cb212dabf3e0ed594a8169d44a113a/src/skimage/measure/fit.py#L899

The article asserts that "the eigenvalues will be three reals, typically one positive and two negatives". The code does not account for these pathological cases though.

**Comment by ev-br** [comment]
And for completeness, _the article_, Ref [1] in the scikit-image code, is https://autotrace.sourceforge.net/WSCG98.pdf

**Comment by steppi** [comment]
> Will it really? To me, it's a pure math thing: eigenvalues of a real matrix are complex-valued. They can --- by accident --- have zero imaginary parts. These zero imaginary parts can --- again, by accident --- become identically zero in floating point, but in general one needs some tolerance to decide if `.imag` is zero or not. And that tolerance is problem-dependent. Just like a matrix rank, which is ill-defined in inexact arithmetic.

I agree with @ev-br that it seems most reasonable for a general eigenvalue finding function that assumes no special structure to return complex values.

Something which I think could be useful is a way to signal intent that one expects the eigenvalues to be real, raising if that isn't the case. This could be done through a keyword argument, or a separate function.  At least if starting from scratch, I think I would prefer a separate function, because like @seberg said here

> Aha? I thought it sometimes fails due to funky lapack/blas implementations. And short of them having terrible bugs that we should maybe not work around, I would assume that is minor numerical inaccuracy.
> But if it is numerical inaccuracy, if scikit-image doesn't just want to remove the `== 0` sanity check then they would need something smarter that finds clear violations but doesn't barf on numerical inaccuracies?

you would want a smarter check than just `== 0`, and such a check will likely need configurable tolerances or something along those lines, and adding kwargs for these to `eig` and `eigvals` alongside the one that signals intent that eigenvalues should be real seems like it would complicate the interface.

> Quite the other way around. I think this is an intrusive change and make things really complicated for linear algebra code. Because it will require checking the imaginary part every time you have an eigvals code. I would argue that this is a change not due to usability improvement but to regularize type system that I don't find sufficiently strong reason about.

@ilayn's concerns here seem valid to me, but I think this could be solved by having a way to show one's intent that eigenvalues should be real. Beyond concerns about type regularity, I think this approach would also better follow the principle of "explicit is better than implicit" from the Zen of Python.

Typically, if you have a matrix and it has some special structure where you know the eigenvalues should be real, it seems very likely that there would be a more efficient way to find them than the Hessenberg reduction followed by QR algorithm that GEEV does. But it's not enough just to know the eigenvalues should be real. An option to say you expect eigenvalues to be real wouldn't be useful for efficiency reasons, but I still think is still useful to signal intent and avoid having to rely on quirky behavior from NumPy, or ones own checks if `eig/eigvals` are changed to always return complex eigenvalues.

I argued for a separate function above, but perhaps a `kwarg` would be better for reducing churn.

**Comment by rgommers** [comment]
> Instead of viewing this discussion as introducing a breaking change, I argue this is a NumPy bug (value-dependent casting) that should have been fixed by NumPy 2.0.

The second half of this is definitely correct - it is value-dependent casting and a bad design, and if we had seen this in time, we would have changed it for NumPy 2.0. Arguably it's a (design) bug, but that's perhaps more in the eye of the beholder. The first half: if we change it, it is technically a breaking change now - with probably limited but certainly nonzero impact, as the issue description shows. 

> Something which I think could be useful is a way to signal intent that one expects the eigenvalues to be real

+1 for that as well, that seems like the right design principle. Doesn't even have to be in NumPy of course, since it's more specialized it could be left to SciPy.

> This was brought up, and I am honestly wondering if it isn't better to just flip it.

I think this is actually a reasonable option. _However_, at the moment the impact is hard to estimate. I think if we want to go this way, we should do what we did for NumPy 2.0 in these cases: identify downstream issues, go fix them to be robust to flipping the switch (this will improve the downstream code as well, like in the scikit-image case), and then give it enough time for downstream to do new releases before actually flipping it. Doing the bug fixes will also give a much better impression of whether this will be too disruptive or not - and if it is, obviously that'll be a blocker.

**Comment by ngoldbaum** [comment]
EDIT Dec 12: This is based on invalid assumptions, see below.

We chatted about this at the last community meeting today and noticed a few cases on github search where people are doing things like `np.eigvals(arr) > 0`, which will error if they get back a complex-valued result.

https://github.com/NajibOdhah/hermespy/blob/5487592051995dc0d7d6104ca49c33e92f415f57/channel/multipath_fading_channel.py#L100
https://github.com/qiskit-community/promised-davies-generator/blob/5b87b130ce69f66449a1aa2a8c26ed3b2628b325/src/lindblad_analysis.py#L95
https://github.com/ihmeuw/dismod_mr/blob/389150ad70b4fe4cee167278402214ede80c1bb6/src/dismod_mr/fit.py#L186

All these cases should almost certainly be using `eigh`. Unfortunately the error they would see if we changed the return type is going to be confusing and unfriendly to deal with.

The discussion in the meeting landed on adding a new keyword argument as an escape hatch and generating a `FutureWarning` if `eig` or `eigvals` returns a real result. That way people who are working with complex numbers already don't have to do anything and people who aren't get some notice about what they need to do to migrate their code. Users who are doing incorrect, buggy linear algebra programming get notice that they are writing buggy code.

It does mean library maintainers need to add some numpy version-dependent code because the keyword argument is new. We thought the benefit of alerting users to buggy code is worth that pain, rather than waiting a few years for projects to only support numpy versions with the new keyword.

**Comment by rgommers** [comment]
@ngoldbaum I don't understand all of that summary. There seems to be a conflict between:

> That way people who are working with complex numbers already don't have to do anything

and

> It does mean library maintainers need to add some numpy version-dependent cod

Can you clarify?

It would also be nice if the summary actually addressed previous arguments (e.g. _"If that is common enough, a warning would be very disruptive with, honestly, relatively little gain."_ and _"I think if we want to go this way, we should do what we did for NumPy 2.0 in these cases ..."_ and "Can we find the solution for scikit-learn!?"). Without that, it feels like the useful discussion here is mostly ignored.
 
The `qiskit` example is fine by the way, it uses `np.real(np.eigvals(`.

**Comment by ngoldbaum** [comment]
> Can you clarify?

I meant that if the function is already returning a complex number for their use, they don't have to do anything.

> It would also be nice if the summary actually addressed previous arguments

Sure, I'll try to do that here. For what it's worth during the discussion yesterday these points didn't stand out to me.

> "If that is common enough, a warning would be very disruptive with, honestly, relatively little gain." and 

This is a quote from @seberg. During the meeting yesterday he seemed to think the examples where comparing with zero are worth caring about.

But actually now that I look closer, maybe I was under a mistaken assumption that this is an error:

```
>>> np.array([1 + 1j, 1 + 3j]) > 0
array([ True,  True])
```

My mistake for not quickly trying that yesterday. So the code examples I found are not worth worrying about, comparisons with 0 won't raise errors. It looks like even scalars behave this way:

```
>>> np.array([1 + 1j, 1 + 3j])[0] > 0
np.True_
```

which is different from built-in complex numbers:

```
>>> 1+1j > 0
Traceback (most recent call last):
  File "<python-input-10>", line 1, in <module>
    1+1j > 0
TypeError: '>' not supported between instances of 'complex' and 'int'
```

My only excuse from the embarrassment here is no one else caught it yesterday either. Very sorry for the confusion.

> "I think if we want to go this way, we should do what we did for NumPy 2.0 in these cases ..." and 

So given what I just found I think I need to change my opinion and instead say that we should just go ahead and flip the switch, once someone has gone ahead and fixed the issues in scikit-learn and we are pretty confident the blast radius of doing so will be small.

**Comment by rgommers** [comment]
Thanks for the clarifications.

> once someone has gone ahead and fixed the issues in scikit-learn and we are pretty confident the blast radius of doing so will be small.

Either way that does seem like the next step here. Possibly fix up the other examples just found as well if using `eigh` is better and it's a one-line quick fix. @ev-br since you're trying to get this over the finish line, would you be able to take this action?

**Comment by ev-br** [comment]
There are no known issues in scikit-learn, at least according to https://github.com/numpy/numpy/pull/30411#issuecomment-3636477320
If I missed something in scikit-learn, could you point me to it?

The `scikit-image` issue does not exist until and unless numpy flips the switch, and my standing offer is to send a patch their way as soon as numpy PR lands (before that, it'd be dead code).

**Comment by rgommers** [comment]
Oh I was going by the comment for scikit-learn, if that was a typo and it meant scikit-image then all good. For scikit-image: the fix should land first, so it's in a release when numpy flips the switch. Don't worry about dead code I think, rolling out a fix before creating a new problem that otherwise would have to be taken care of quickly is is the right order.

**Comment by ngoldbaum** [comment]
Sorry, I meant scikit-image. I always conflate them when I type.

**Comment by stefanv** [comment]
Came here after debugging the same issue on skimage nightly CI. I can see the arguments both ways, but long run probably helpful to have the return type be consistent. Mainly, just wanted to thank @ev-br for taking the time to make a pre-emptive bugfix.

**Comment by seberg** [comment]
I guess we can close this issue. That said, if anyonehas larger fallout, please comment so we at least know (and if just to improve docs, but also possibly revert --this hadto wave deprecation periods after all).
