### ISSUE TITLE
BUG: `SystemError` from np.dot when given certain incompatible types.

### ISSUE THREAD

**Issue by WarrenWeckesser** [numpy/numpy#29688]
### Describe the issue:

This was observed in SciPy: https://github.com/scipy/scipy/issues/23561. That was with numpy 2.2.6, but the problem occurs in the main development branch too.

Here's a simple reproducer:

```
In [52]: np.__version__
Out[52]: '2.4.0.dev0+git20250905.8339bce'

In [53]: a = np.zeros((2, 2), dtype=complex)

In [54]: b = np.array([[np.timedelta64(123, 's')], [np.timedelta64(321, 's')]], dtype=object)

In [55]: np.dot(a, b)
---------------------------------------------------------------------------
UFuncTypeError                            Traceback (most recent call last)
UFuncTypeError: ufunc 'multiply' cannot use operands with types dtype('complex128') and dtype('<m8[s]')

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
Cell In[55], line 1
----> 1 np.dot(a, b)

SystemError: <built-in method __subclasscheck__ of numpy._DTypeMeta object at 0x7936970ce500> returned a result with an exception set
```
The `TypeError` looks reasonable, but the `SystemError` does not.

### Reproduce the code example:

```python
See above.
```

### Error message:

```shell
See above.
```

### Python and NumPy Versions:

2.4.0.dev0+git20250905.8339bce
3.13.7 (main, Sep  4 2025, 21:56:53) [GCC 11.4.0]

**Comment by seberg** [comment]
The annoyance is that the old Array functions don't return errors.  So what happens is that `OBJECT_dot` sets an error, but then continues with an error set.

That kinda somewhat works, but the second call is then done with an error set and that is just wrong.  It then triggers the ufunc promotion step or so to fail, but basically the how it fails the second time is irrelevant, the problem is continueing to work there.

To paper that over, we could check for `PyErr_Occurred()` inside the `OBJECT_dot` function, that is probably the easiest.  Or check wherever it is called (if the GIL is held).

**Comment by rgommers** [comment]
I'm not sure if this issue should be fixed or not - it may be worth it in this case - but not that this came from someone running Hypothesis at scale rather than from anything real world relevant: https://github.com/scipy/scipy/issues/23555#issuecomment-3288578297

**Comment by Lawson-Darrow** [comment]
On current main, `OBJECT_dot` still has no `PyErr_Occurred()` check, so this `SystemError` is still reproducible. I'd be glad to implement seberg's suggestion (bail out when an error is already set instead of continuing into the promotion path). 

Given like you mentioned that the note surfaced from Hypothesis rather than a real-world case, is this something you still want fixed? @rgommers Happy to do it if there's appetite, or to leave it be if it's not worth the churn.

**Comment by seberg** [comment]
It's just very low priority so if you or someone else wants to add it, maybe just make a small benchmark (no need for a real benchmark) to show that it is pretty much unnoticeable to fix (and make sure to add a tiny test).
