### ISSUE TITLE
BUG: Multithreaded scaling bottlenecks on free-threaded Python

### ISSUE THREAD

**Issue by ngoldbaum** [numpy/numpy#30494]
[This stackoverflow question](https://stackoverflow.com/questions/79851420/multithreading-becomes-much-slower-than-multiprocessing-in-free-threaded-python#79851420) seems to have identified two real scaling bottlenecks inside NumPy.

I build Python 3.15t from source using pyenv:

```
$ CFLAGS=-O2 pyenv install 3.15t-dev -k -g
...
$ pyenv global 3.15t-dev-debug
```

Then, in an up-to-date clone of the NumPy repo:

```
python -m pip install . -v -Cbuilddir=build -C'setup-args=-Dbuildtype=debugoptimized'
```

And finally run this script, which has to be named `mtmp.py`: https://gist.github.com/ngoldbaum/ff6428e2510e991247eba4c809dcc8ac. This is identical to what was posted on StackOverflow but with some code commented out.

On my M3 Macbook Pro, I get the following stdout running the script:

```
Inner loops 10, multithreading  time: 6.68 sec, result sum: 717434683.1879175
Inner loops 10, multiprocessing time: 4.86 sec, result sum: 717434683.1879175
```

If I run the script like so:

```
PYTHONPERFSUPPORT=1 samply record $(pyenv which python) mtmp.py
```

Then I get a profile output like this: https://share.firefox.dev/3Lde1Lm. I see two different scaling bottlenecks. First, there seem to be a mutex inside tracemalloc that has contention.

Second, the critical section I added to the array creation routines in https://github.com/numpy/numpy/pull/29394 is causing some contention in this case.

**Comment by ngoldbaum** [comment]
If you're unfamiliar with how to read firefox profiles, here's a flame graph from one of the thread pool threads in the profile, which makes it clearer that most of the time is being spent waiting to acquire PyMutex locks in tracemalloc and in the array creation routines. 

<img width="1468" height="473" alt="Image" src="https://github.com/user-attachments/assets/23e964e4-0ed7-4fb7-a9a8-304e9eecee39" />

**Comment by chris-eibl** [comment]
Here are numbers for Python 3.14.2 using [Python install manager](https://www.python.org/ftp/python/pymanager/python-manager-25.2.msix) and `numpy-2.4.0-cp314-cp314t-win_amd64.whl` on my 4 core Haswell i5-4570 on Windows 10:

`n_core = 1:`

```
Inner loops 1,  multithreading  time: 4.43 sec, result sum: 66993532.26748921
Inner loops 1,  multiprocessing time: 9.81 sec, result sum: 66993532.26748921

Inner loops 10, multithreading  time: 42.22 sec, result sum: 717434683.1879117
Inner loops 10, multiprocessing time: 44.37 sec, result sum: 717434683.1879117
```

`n_core = 4:`

```
Inner loops 1,  multithreading  time: 1.25 sec, result sum: 66993532.26748953
Inner loops 1,  multiprocessing time: 4.35 sec, result sum: 66993532.26748953

Inner loops 10, multithreading  time: 11.78 sec, result sum: 717434683.1879193
Inner loops 10, multiprocessing time: 13.61 sec, result sum: 717434683.1879193
```

So scales well on my setup and mt performs better than mp.

Maybe this depends on the OS or I need more cores to suffer from this?

**Comment by charlieCoalition** [comment]
@chris-eibl Thank you for testing. In my SO post I did test it on a Windows 11 Dell laptop with 8 Intel physical cores (16 logical cores) and I didn't see it scale. I also updated the post with testing `list` instead of numpy array and it did scale well. Interesting problem..

**Comment by ngoldbaum** [comment]
I reported the tracemalloc issue upstream: https://github.com/python/cpython/issues/143057. Thankfully that should be a straightforward fix and also is something that can be backported, so it'll hopefully be fixed in Python 3.14.3.

**Comment by ngoldbaum** [comment]
@charlieCoalition if you notice any more mulithreaded scaling issues like this please feel free to open a NumPy issue and ping me. I'm currently working full-time to improve ecosystem support for free-threaded Python and this is well within that scope. We've also been looking for real-world scaling issues just like this.

**Comment by chris-eibl** [comment]
> I did test it on a Windows 11 Dell laptop with 8 Intel physical cores (16 logical cores)

Tested now on Win 11 AMD Ryzen 7 5800X (8 physical / 16 logical) and for `n_core = 8` and `n_core = 16` still mt was better than mp for me. But unsurprisingly, when overcommitting it gets worse the more threads are used.

**Comment by kumaraditya303** [comment]
I have fixed this upstream in https://github.com/python/cpython/pull/143065 and will be backported to 3.14.

**Comment by ngoldbaum** [comment]
> I have fixed this upstream in https://github.com/python/cpython/pull/143065 and will be backported to 3.14.

Thanks, I confirm that multithreading now beats multiprocessing:

Here's the flame graph I get now:

<img width="1492" height="375" alt="Image" src="https://github.com/user-attachments/assets/b9ee0f4f-1c33-44af-bb55-7d3771c27c22" />

Good: we're now spending more time inside the `sin` and `cos` implementations, which is where we want to be.

Bad: There's some contention to acquire a critical section in `convert_ufunc_arguments`, ultimately called by the `array_add` implementation. Because this is all in NumPy internals I wonder if there's a way we can know statically that there's no mutation going on and the critical section is unnecessary. But maybe it is necessary? Or maybe we should not worry so much about people trying to break NumPy by mutating the argument of `np.array()` while an array is being created in another thread.

There's also a bit of contention in the `shared_mutex` in the promotion cache. Maybe @kumaraditya303 PyMutex-based RWLock will perform better (see https://github.com/numpy/numpy/pull/30275).

Also see [the full profile](https://share.firefox.dev/45kngQE) for more detail.

**Comment by ngoldbaum** [comment]
For the array coercion critical section: one thing we can do right now is skip it when immutable data are passed in. So we could check for lists vs tuples, for example. We can also maybe check the readonly flag?

For the `shared_mutex` i'm increasingly thinking we should bite the bullet and implement the suggestion in https://github.com/numpy/numpy/pull/30275#issuecomment-3572007197. The `shared_mutex` I get from the Apple Clang LibC++ seems to hit a slow path - even for shared reads with no writes (as fast as I can see, maybe I'm missing something).

**Comment by charlieCoalition** [comment]
@ngoldbaum Hi Nathan, thank you for solving the problem! I don't have the bandwidth now to fully understand the numpy internals in ur last post, but could i ask a related question about the best habit of using numpy in a multithreaded environment?

if I only (i) **read** the data that threads can see, and (ii) **create** new numpy arrays in each thread during parallelization, and (iii) allow no thread communication before the final join, will the bottleneck _mostly_ depend on the concurrent efficiency of low-level allocators like `malloc`? And I say _mostly_ because i'm sure great (compared to C-level) overhead exists in the Python layer so we shouldn't let threads create many small numpy arrays or work on trivial tasks.

Is your "coercion critical section" saying that even the **read** in (i) is synced? Is this a numpy or Python characteristic?
Thanks!

**Comment by charlieCoalition** [comment]
@ngoldbaum I just installed the 3.14t dev version from github, and here is the benchmark:

<img width="1708" height="244" alt="Image" src="https://github.com/user-attachments/assets/2a469ab1-027f-4d9d-a451-94ae2583221d" />

Multithreading time was cut in half but still slightly slower than multiprocessing.. Is this caused by reasons stated in ur last post?:D

It seems the slowdown also largely depends on machine. Mine is Apple M4 Pro (14 cores)

Update: if I change the inner loops to 30, things become much worse:(

<img width="1734" height="246" alt="Image" src="https://github.com/user-attachments/assets/9c310b1d-7014-4876-8848-ea76292901a8" />

**Comment by ngoldbaum** [comment]
> Multithreading time was cut in half but still slightly slower than multiprocessing.. Is this caused by reasons stated in ur last post?:D

Yes, there are still some scaling issues in your script that this issue is tracking. I spoke with @kumaraditya303 and I think the plan is for him to implement the suggestion in https://github.com/numpy/numpy/pull/30275#issuecomment-3572007197 which will allow us to avoid any locking in the fast path for the promotion cache.

The other thing I think we should do is get rid of the critical section in the array creation code and instead document that mutating the argument of `np.array()` while creating an array is unsafe. I'm going to submit a pull request for that.

**Comment by charlieCoalition** [comment]
@ngoldbaum Hopefully after the updates above multithreading will be as fast as multiprocessing even when `n_loop = 30`:D

**Comment by kumaraditya303** [comment]
https://github.com/kumaraditya303/numpy/tree/fast-cache is my WIP branch which implements the lock-free promotion cache and removes the critical section while creating `ndarray`. 

With the lock-free cache implementation, multithreading is now faster than multiprocessing.
```console
Inner loops 10, multithreading  time: 2.88 sec, result sum: 717434683.1879176
Inner loops 10, multiprocessing time: 3.58 sec, result sum: 717434683.1879176
```

I profiled it using `samply` and most of time is now spent in `cos` and `sin` and there's no contention in the cache lookup: https://share.firefox.dev/48VBPN5

<img width="1440" height="358" alt="Image" src="https://github.com/user-attachments/assets/c872ab54-f41a-4161-9433-9d3c3cea14e0" />

**Comment by charlieCoalition** [comment]
@kumaraditya303 Thank you very much for the work! May I ask what if `Inner loops` changed to 30?

**Comment by kumaraditya303** [comment]
> May I ask what if Inner loops changed to 30?

Both multithreading and multiprocessing perform almost equally:
```console
❯  python  mtmp.py
Inner loops 30, multithreading  time: 8.49 sec, result sum: 2169064187.9531527
Inner loops 30, multiprocessing time: 8.54 sec, result sum: 2169064187.9531527
```

**Comment by charlieCoalition** [comment]
```
Inner loops 30, multithreading  time: 6.24 sec, result sum: 2169064187.9531517
Inner loops 30, multiprocessing time: 4.75 sec, result sum: 2169064187.9531517

```
Sadly on Apple M4 Pro (14 cores) the speed is improved but still notably slower than multiprocessing..

**Comment by ngoldbaum** [comment]
@charlieCoalition are you sure you're using Kumar's branch and either the `3.14` or `main` branch of CPython? Otherwise you'll be hitting the tracemalloc scaling issue which hasn't been fixed in a released Python version yet.

**Comment by ngoldbaum** [comment]
And if you are doing that, please share a profile.

**Comment by charlieCoalition** [comment]
I am definitely using the newly updated (a few days back by @kumaraditya303 ) Python3.14t branch and the newly updated numpy today. I saw a significant multithreading speedup after switching to the newest Python3.14t, and then an additional significant speedup when using the newest numpy. It's just multithreading speed falls behind multiprocessing. As u can see @kumaraditya303 's time costs for `n_loop=10` vs `n_loop=30`, the slowdown becomes more pronounced  with increasing `n_loop`. I'll include profile soon

**Comment by charlieCoalition** [comment]
https://share.firefox.dev/4919UtC

**Comment by ngoldbaum** [comment]
It looks like you didn't build NumPy or CPython with debug symbols. Not sure how you're building both but you can do that for NumPy at least by installing NumPy with e.g. `python -m pip install . -v -Cbuilddir=build -C'setup-args=-Dbuildtype=debugoptimized'` in a checkout of the NumPy repo. For CPython I build Python manually using pyenv, where I can pass `-g` to get a debug python build.

It also looks like there's only one process in the process pool - not sure what's up with that. It'd help to see the script you're running if there are any local modifications.

**Comment by kumaraditya303** [comment]
> https://share.firefox.dev/4919UtC

The profile shows calls to `tan` so it seems to be different script, the original reproducer does not contain any `tan` calls.

**Comment by charlieCoalition** [comment]
sorry for the late reply! And https://share.firefox.dev/4jezSP0 is the newest profile. I reinstalled `python` from https://github.com/python/cpython/tree/3.14 and `numpy` from https://github.com/kumaraditya303/numpy/tree/fast-cache, ensured `-g`.  Below is `mtmp.py`

```
import numpy as np
import os
from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor

# `x` is referenced `n_loop` times.
def kernel(x, n_loop):
    return sum((np.sin(np.cos(np.sin(np.cos(x + i)))).sum() 
        for i in range(n_loop)))

def worker(group, n_loop):
    return sum(kernel(g, n_loop) for g in group)

if __name__ == '__main__':
    import sys
    print("Python version is free-threaded:", not sys._is_gil_enabled())
    vsize = 500
    n = 100000
    np.random.seed(42)

    X = [np.random.uniform(size = vsize) for _ in range(n)]
    n_core = os.cpu_count()
    dx = len(X) // n_core + 1
    Xgroups = []
    for i in range(0, len(X), dx):
        Xgroups.append(X[i:min(i+dx, len(X))])

    import time, mtmp

    n_loop = 50

    st = time.time()
    with ProcessPoolExecutor(max_workers = n_core) as pool:
        futures = [pool.submit(mtmp.worker, g, n_loop) for g in Xgroups]
        workerRsts = [future.result() for future in futures]
    print(f"Inner loops {n_loop}, multiprocessing time: { \
        time.time() - st:.2f} sec, result sum: {sum(workerRsts)}")

    st = time.time()
    with ThreadPoolExecutor(max_workers = n_core) as pool:
        futures = [pool.submit(mtmp.worker, g, n_loop) for g in Xgroups]
        workerRsts = [future.result() for future in futures]
    print(f"Inner loops {n_loop}, multithreading  time: { \
        time.time() - st:.2f} sec, result sum: {sum(workerRsts)}")

```
It printed the following:
```
Python version is free-threaded: True
Inner loops 50, multiprocessing time: 4.08 sec, result sum: 1807379779.5481863
Inner loops 50, multithreading  time: 11.09 sec, result sum: 1807379779.5481863
```
My machine is Apple M4 14 cores.

I seriously don't understand why `tan()` was called in my last run. My last python build was using GCC rather than Clang.

Please let me know if you see similar output on ur machine..:D Thank you!

**Comment by charlieCoalition** [comment]
@ngoldbaum seems in https://share.firefox.dev/4jezSP0 you would need to select all the tracks to see all processes spawned from the main

<img width="346" height="224" alt="Image" src="https://github.com/user-attachments/assets/fd187db4-5549-4e3e-8bd7-081f2952f96a" />

In the new `mtmp.py` I put multiprocessing before multithreading to counter the caching effect. I saw multiprocessing become faster if the order is reversed.

**Comment by ngoldbaum** [comment]
It looks like you're seeing a lot of reference count contention. I'm not seeing that over here on my M3 Macbook Pro running the same script and Kumar's branch of NumPy.

One thing to keep in mind with your M4 macbook pro is that you have both performance and efficiency cores. You'll probably see better scaling if you limit the core count to just performance cores. Getting good multithreaded scaling with heterogenous compute is hard.

All that said, I don't see nearly as bad performance over here on my M3 Max Macbook Pro with 11 cores and 4 performance cores:

```
Inner loops 50, multiprocessing time: 8.68 sec, result sum: 1807379779.5481868
Inner loops 50, multithreading  time: 10.20 sec, result sum: 1807379779.5481868
```

I'm also seeing some reference count contention, but not nearly as bad: https://share.firefox.dev/490g5zD.

If I set `n_core = 4` in your script, I get the following results:

```
Inner loops 50, multiprocessing time: 12.70 sec, result sum: 1807379779.548181
Inner loops 50, multithreading  time: 12.43 sec, result sum: 1807379779.548181
```

Which is closer to perfect scaling, albeit a little slower. Not sure why reference counting scales so much more poorly on your efficiency cores than on mine.

https://share.firefox.dev/4q3NGi4

**Comment by charlieCoalition** [comment]
@ngoldbaum Thank you for the the answer and this is so unfortunate.. 

```
system_profiler SPHardwareDataType | grep "Cores" 
Total Number of Cores: 14 (10 performance and 4 efficiency)
```
I set `n_core = 10`, and here is the result:
```
Python version is free-threaded: True
Inner loops 50, multiprocessing time: 4.74 sec, result sum: 1807379779.548188
Inner loops 50, multithreading  time: 9.37 sec, result sum: 1807379779.548188
```
So in the end, the killer is still reference counting which won't be fixed in foreseeable future?

**Comment by ngoldbaum** [comment]
> So in the end, the killer is still reference counting which won't be fixed in foreseeable future?

I think it's more that you're seeing us fix multithreaded scaling issues and we can't know what the next worst scaling issue is until we fix the existing biggest issue. There's still more we can do to improve things. See below.

I suspected something funky happening and to test that, I rewrote the script so there is no shared data between the worker threads:

<details>

```
import numpy as np
import time
from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor

# `x` is referenced `n_loop` times.
def kernel(n_loop, seed):
    vsize = 500
    rng = np.random.RandomState()
    rng.seed(seed)
    return sum((np.sin(np.cos(np.sin(np.cos(rng.uniform(size=vsize) + i)))).sum()
        for i in range(n_loop)))

def worker(n_loop, n_workers):
    return sum(kernel(n_loop, i) for i in range(n_workers))

if __name__ == '__main__':
    import sys
    print("Python version is free-threaded:", not sys._is_gil_enabled())
    n = 100000
    np.random.seed(42)

    n_workers = 50
    n_loop = 100

    st = time.time()
    with ProcessPoolExecutor(max_workers = n_workers) as pool:
        futures = [pool.submit(worker, n_loop, n_workers) for _ in range(n_workers)]
        workerRsts = [future.result() for future in futures]
    print(f"Inner loops {n_loop}, multiprocessing time: { \
        time.time() - st:.2f} sec, result sum: {sum(workerRsts)}")

    st = time.time()
    with ThreadPoolExecutor(max_workers = n_workers) as pool:
        futures = [pool.submit(worker, n_loop, n_workers) for _ in range(n_workers)]
        workerRsts = [future.result() for future in futures]
    print(f"Inner loops {n_loop}, multithreading  time: { \
        time.time() - st:.2f} sec, result sum: {sum(workerRsts)}")
```

</details>

I also cranked up `n_loop` and `n_workers` to make the scaling issues more glaring.

I still see some multithreaded scaling issues here due to global state in NumPy. See this profile: https://share.firefox.dev/3YLcFuu.

I think the problem is that even though NumPy's allocator is stored in a context variable, that doesn't mean that the handler is automatically thread-local. Instead, I think because the allocator context variable just uses `PyDataMem_DefaultHandler` as the default value, that means that each worker by default uses the global allocator and that leads to contention. Both refcount contention and also heap contention inside `malloc`.

See here: https://github.com/numpy/numpy/blob/e017416123fe471c9a3f9a36bcb98223fd7cba1d/numpy/_core/src/multiarray/multiarraymodule.c#L5180. The second argument to `PyContextVar_New` is the default value.

Instead, we probably want a per-thread PyCapsule pointer to the allocator? That'll help the refcount contention.

For the `malloc` contention, it'll probably help to turn on the allocator cache for all these small allocations in your script, see #30499.

**Comment by colesbury** [comment]
@ngoldbaum - I was just writing a comment and you beat me to it. `PyDataMem_DefaultHandler` is a global that's never freed, so I think we can just make it immortal.

That seems to help a lot. I have an M4 Pro as well and the FT threads test goes from ~8.6 second to ~6.21 seconds with that change. Still slower than multiprocessing at 4.7s econds.

The other bottleneck I saw was in `_Py_module_getattro_impl`.

**Comment by ngoldbaum** [comment]
I created a branch with all of the WIP optimizations we're working on as well as @colesbury's suggestion to make the memory handler immortal. I also noticed a similar reference counting contention issue with the floating point exception handler PyCapsule and made that immortal as well. You can pull the [`fast-cache` branch](https://github.com/numpy/numpy/compare/main...ngoldbaum:numpy:fast-cache?expand=1) from my fork of NumPy to get the code.

With that code and [this script](https://gist.github.com/ngoldbaum/b01b00365498acc73e27eba4c1dfc401) which sets `n_workers` and `n_loop` to 50, I get the following profile: https://share.firefox.dev/3L48gjb. On my Mac developer machine, multithreading beats multiprocessing by a 10% margin.

I also ran the script using jemalloc, which does seem to help a little but it doesn't fix the malloc contention I see in the profile. The allocator cache is turned on but it doesn't seem like it helps much. Maybe there's more we can do to improve allocation caching so there are fewer cache misses?

I also see a small scaling issue in `_Py_module_getattro_impl `. I also see an opportunity to maybe get a tiny performance boost by bypassing the `name_matches` check inside the `PyCapsule_GetPointer` implementation. Maybe there's room for a variant that doesn't check the capsule name?

After that, I don't see any more obvious multithreaded bottlenecks. Everything else looks like code from the core ufunc loop, reductions, or scalar math.

**Comment by charlieCoalition** [comment]
@ngoldbaum  https://share.firefox.dev/4jgonGO

Multithreading speed improved again (Apple M4 14 cores, `n_core = 14`):
```
Python version is free-threaded: True
Inner loops 50, multiprocessing time: 4.08 sec, result sum: 1807379779.5481863
Inner loops 50, multithreading  time: 5.76 sec, result sum: 1807379779.5481863
```
Although it's still slower than multiprocessing.

Dumb question: if the waste is concentrated within C allocators like `malloc`, wouldn't multiprocessing also suffer if not more? 

Oh and with `n_core = 10` (10 performance cores):
```
Python version is free-threaded: True
Inner loops 50, multiprocessing time: 4.68 sec, result sum: 1807379779.548188
Inner loops 50, multithreading  time: 6.03 sec, result sum: 1807379779.548188
```
Thanks for all the helps!

**Comment by ngoldbaum** [comment]
> Dumb question: if the waste is concentrated within C allocators like malloc, wouldn't multiprocessing also suffer if not more?

Each process in the process pool is requesting memory with its own per-process allocator. For the multithreaded case, all the threads are sharing the same allocator and heap. I'm not sure offhand if there's a trick we can do to improve things in the multithreaded case.

In any case, it looks like on your system the malloc contention isn't as bad as on my system. The scaling issue in `_Py_module_getattro_impl` is a bigger problem for you. It sounds like you and @colesbury are on similar machines.

**Comment by ngoldbaum** [comment]
One thing that will help is to write your kernel function like this:

```
cos = np.cos
sin = np.sin

# `x` is referenced `n_loop` times.
def kernel(x, n_loop):
    return sum((sin(cos(sin(cos(x + i)))).sum()
        for i in range(n_loop)))
```

That avoids the module attribute lookup in the fast path.

**Comment by charlieCoalition** [comment]
@ngoldbaum Thanks! I thought eventually the hotspot would trace back to OS in both mulproc and multhread but probably u r right especially when smaller allocations are frequent. fyi, in the past I extensively use this allocator https://cmuparlay.github.io/parlaylib/other/allocator.html whose performance is often astonishing. However the speed is a tradeoff of memory since it allocates power-of-two bytes for larger buffers. Curious if `numpy` did or would implement its own memory allocator for multithreaded computing.

And thank you for the tips on attribute lookup! It does help a little!:D:
```
Python version is free-threaded: True
Inner loops 50, multiprocessing time: 4.62 sec, result sum: 1807379779.548188
Inner loops 50, multithreading   time:  5.93 sec, result sum: 1807379779.548188
```

**Comment by kumaraditya303** [comment]
I have fixed the `_Py_module_getattro_impl` contention upstream in https://github.com/python/cpython/commit/faa3dc7c64b7bda4e74c7630be4c873e0b58a569.

**Comment by kumaraditya303** [comment]
The lock-free hashtable for ufunc dispatching is merged now https://github.com/numpy/numpy/pull/30593 so I think the only remaining part is making some of the shared objects immortal.

**Comment by ngoldbaum** [comment]
There were no objections in my D.P.O thread, so I think the next step is to add the new unstable API function following the docs I suggested:

https://discuss.python.org/t/add-an-unstable-c-api-for-immortalizing-objects/105461/7

I'm planning to get to that soonish but if anyone else wants to try, please feel free.

Once that's in we need to add a backport to the pythoncapi-compat header and then we can use it in NumPy.

**Comment by charlieCoalition** [comment]
Since `Python 3.14.3` is out, I just tested it with the latest `numpy 2.4.2` on mac M4 14 core. The script is still `mtmp.py`:
```
import numpy as np
import os
from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor

# `x` is referenced `n_loop` times.
def kernel(x, n_loop):
    return sum((np.sin(np.cos(np.sin(np.cos(x + i)))).sum() 
        for i in range(n_loop)))

def worker(group, n_loop):
    return sum(kernel(g, n_loop) for g in group)

if __name__ == '__main__':
    import sys
    print("Python version is free-threaded:", not sys._is_gil_enabled())
    vsize = 500
    n = 100000
    np.random.seed(42)

    X = [np.random.uniform(size = vsize) for _ in range(n)]
    # n_core = os.cpu_count()
    n_core = 10
    dx = len(X) // n_core + 1
    Xgroups = []
    for i in range(0, len(X), dx):
        Xgroups.append(X[i:min(i+dx, len(X))])

    import time, mtmp

    n_loop = 50

    st = time.time()
    with ProcessPoolExecutor(max_workers = n_core) as pool:
        futures = [pool.submit(mtmp.worker, g, n_loop) for g in Xgroups]
        workerRsts = [future.result() for future in futures]
    print(f"Inner loops {n_loop}, multiprocessing time: { \
        time.time() - st:.2f} sec, result sum: {sum(workerRsts)}")

    st = time.time()
    with ThreadPoolExecutor(max_workers = n_core) as pool:
        futures = [pool.submit(mtmp.worker, g, n_loop) for g in Xgroups]
        workerRsts = [future.result() for future in futures]
    print(f"Inner loops {n_loop}, multithreading  time: { \
        time.time() - st:.2f} sec, result sum: {sum(workerRsts)}")
```

Run `samply record -- PYTHONPERFSUPPORT=1 python3.14t mtmp.py`:
```
Python version is free-threaded: True
Inner loops 50, multiprocessing time: 5.17 sec, result sum: 1807379779.548188
Inner loops 50, multithreading  time: 12.82 sec, result sum: 1807379779.548188
```

samply graph is at https://share.firefox.dev/4tlISqd . 

Hopefully this helps.

Interesting to see even `array_add` and `array_sum` took more time on in multithreading than multiprocessing..

**Comment by kumaraditya303** [comment]
You should use the latest main branch of numpy which has lock-free hashtable implementation.

**Comment by charlieCoalition** [comment]
@kumaraditya303 Will the lock-free hashtable implementation be released in the next version of numpy? Thank you!

**Comment by ngoldbaum** [comment]
It will be in Numpy 2.5, due out this summer.

We didn't backport it because it's a significant change to internals and we wanted to test it in `main` for a while before releasing it to the world.

**Comment by charlieCoalition** [comment]
Just in case this is still interesting - samply graph at https://share.firefox.dev/4kpQa8p using `numpy 2.5.0 dev`. Also
```
Python version is free-threaded: True
Inner loops 50, multiprocessing time: 4.78 sec, result sum: 1807379779.548188
Inner loops 50, multithreading  time: 8.39 sec, result sum: 1807379779.548188
```
Improved again:D

**Comment by ngoldbaum** [comment]
@kumaraditya303 implemented and merged `PyUnstable_SetImmortal`: https://github.com/python/cpython/pull/144543. It looks like it got in *just* in time for 3.15a6, woohoo!

The next step is to update the pythoncapi-compat headers to expose this new function using private internals on older Python versions (including 3.14). Then we can make the global PyCapsules immortal (c.f. https://github.com/numpy/numpy/issues/30494#issuecomment-3697570953 and replies), which will help with reference count contention in this benchmark.

**Comment by charlieCoalition** [comment]
Just installed `Python 3.15.0a6+` and `numpy 2.5.0.dev0+git20260212.7a205df` on 
```
Model Name: MacBook Pro
Chip: Apple M4 Pro
Total Number of Cores: 14 (10 Performance and 4 Efficiency)
Memory: 48 GB
```
Running `mtmp.py` produces samply graph at https://share.firefox.dev/4kyjGJk and the following
```
Python version is free-threaded: True
Inner loops 50, multiprocessing time: 4.75 sec, result sum: 1807379779.548188
Inner loops 50, multithreading  time: 8.31 sec, result sum: 1807379779.548188
```

**Comment by ngoldbaum** [comment]
@charlieCoalition mind trying again with a checkout of #30826?

**Comment by charlieCoalition** [comment]
@ngoldbaum Could be my problem as I haven't read through the links above, but I got this error:
```
  In file included from ../numpy/_core/src/multiarray/scalartypes.c.src:16:
  In file included from ../numpy/_core/src/common/npy_pycompat.h:5:
  ../numpy/_core/src/common/pythoncapi-compat/pythoncapi_compat.h:2668:1: error: static declaration of 'PyUnstable_SetImmortal' follows non-static declaration
   2668 | PyUnstable_SetImmortal(PyObject *op)
        | ^
  /Users/charlie.liu/Desktop/hackumulation-v2/charliesWork/temp/pythonGitMain/include/python3.15t/cpython/object.h:497:17: note: previous declaration is here
    497 | PyAPI_FUNC(int) PyUnstable_SetImmortal(PyObject *op);
        |                 ^
  1 error generated.
  [146/329] Linking static target numpy/_core/libunique_hash.a
  [147/329] Compiling C object numpy/_core/_multiarray_umath.cpython-315t-darwin.so.p/meson-generated_loops.c.o
  FAILED: [code=1] numpy/_core/_multiarray_umath.cpython-315t-darwin.so.p/meson-generated_loops.c.o
  cc -Inumpy/_core/_multiarray_umath.cpython-315t-darwin.so.p -Inumpy/_core -I../numpy/_core -Inumpy/_core/include -I../numpy/_core/include -I../numpy/_core/src/common -I../numpy/_core/src/multiarray -I../numpy/_core/src/npymath -I../numpy/_core/src/umath -I../numpy/_core/src/highway -I/Users/charlie.liu/Desktop/hackumulation-v2/charliesWork/temp/pythonGitMain/include/python3.15t -I/private/var/folders/z5/4406xbpj6ld8jdbn676dh8980000gp/T/pip-req-build-1ysqao3l/.mesonpy-uicmxj22/meson_cpu -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG -Wall -Winvalid-pch -std=c11 -O3 -fno-strict-aliasing -ftrapping-math -DNPY_HAVE_CLANG_FPSTRICT -DNPY_HAVE_NEON_VFPV4 -DNPY_HAVE_NEON_FP16 -DNPY_HAVE_NEON -DNPY_HAVE_ASIMD -F/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Accelerate.framework -idirafter/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Accelerate.framework/Headers -DACCELERATE_NEW_LAPACK -DHAVE_CBLAS '-DBLAS_SYMBOL_SUFFIX=$NEWLAPACK' -DNPY_INTERNAL_BUILD -DHAVE_NPY_CONFIG_H -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -MD -MQ numpy/_core/_multiarray_umath.cpython-315t-darwin.so.p/meson-generated_loops.c.o -MF numpy/_core/_multiarray_umath.cpython-315t-darwin.so.p/meson-generated_loops.c.o.d -o numpy/_core/_multiarray_umath.cpython-315t-darwin.so.p/meson-generated_loops.c.o -c numpy/_core/_multiarray_umath.cpython-315t-darwin.so.p/loops.c
  In file included from ../numpy/_core/src/umath/loops.c.src:19:
  In file included from ../numpy/_core/src/common/npy_pycompat.h:5:
  ../numpy/_core/src/common/pythoncapi-compat/pythoncapi_compat.h:2668:1: error: static declaration of 'PyUnstable_SetImmortal' follows non-static declaration
   2668 | PyUnstable_SetImmortal(PyObject *op)
        | ^
  /Users/charlie.liu/Desktop/hackumulation-v2/charliesWork/temp/pythonGitMain/include/python3.15t/cpython/object.h:497:17: note: previous declaration is here
    497 | PyAPI_FUNC(int) PyUnstable_SetImmortal(PyObject *op);
        |                 ^
  1 error generated.
  [148/329] Compiling Cython source /private/var/folders/z5/4406xbpj6ld8jdbn676dh8980000gp/T/pip-req-build-1ysqao3l/numpy/random/_common.pyx
  [149/329] Compiling C object numpy/_core/_multiarray_umath.cpython-315t-darwin.so.p/src_multiarray_abstractdtypes.c.o
  [150/329] Compiling C object numpy/_core/_multiarray_umath.cpython-315t-darwin.so.p/meson-generated_scalarmath.c.o
  FAILED: [code=1] numpy/_core/_multiarray_umath.cpython-315t-darwin.so.p/meson-generated_scalarmath.c.o
  cc -Inumpy/_core/_multiarray_umath.cpython-315t-darwin.so.p -Inumpy/_core -I../numpy/_core -Inumpy/_core/include -I../numpy/_core/include -I../numpy/_core/src/common -I../numpy/_core/src/multiarray -I../numpy/_core/src/npymath -I../numpy/_core/src/umath -I../numpy/_core/src/highway -I/Users/charlie.liu/Desktop/hackumulation-v2/charliesWork/temp/pythonGitMain/include/python3.15t -I/private/var/folders/z5/4406xbpj6ld8jdbn676dh8980000gp/T/pip-req-build-1ysqao3l/.mesonpy-uicmxj22/meson_cpu -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG -Wall -Winvalid-pch -std=c11 -O3 -fno-strict-aliasing -ftrapping-math -DNPY_HAVE_CLANG_FPSTRICT -DNPY_HAVE_NEON_VFPV4 -DNPY_HAVE_NEON_FP16 -DNPY_HAVE_NEON -DNPY_HAVE_ASIMD -F/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Accelerate.framework -idirafter/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Accelerate.framework/Headers -DACCELERATE_NEW_LAPACK -DHAVE_CBLAS '-DBLAS_SYMBOL_SUFFIX=$NEWLAPACK' -DNPY_INTERNAL_BUILD -DHAVE_NPY_CONFIG_H -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -MD -MQ numpy/_core/_multiarray_umath.cpython-315t-darwin.so.p/meson-generated_scalarmath.c.o -MF numpy/_core/_multiarray_umath.cpython-315t-darwin.so.p/meson-generated_scalarmath.c.o.d -o numpy/_core/_multiarray_umath.cpython-315t-darwin.so.p/meson-generated_scalarmath.c.o -c numpy/_core/_multiarray_umath.cpython-315t-darwin.so.p/scalarmath.c
  In file included from ../numpy/_core/src/umath/scalarmath.c.src:27:
  In file included from ../numpy/_core/src/common/binop_override.h:8:
  In file included from ../numpy/_core/src/common/get_attr_string.h:5:
  In file included from ../numpy/_core/src/common/npy_pycompat.h:5:
  ../numpy/_core/src/common/pythoncapi-compat/pythoncapi_compat.h:2668:1: error: static declaration of 'PyUnstable_SetImmortal' follows non-static declaration
   2668 | PyUnstable_SetImmortal(PyObject *op)
        | ^
  /Users/charlie.liu/Desktop/hackumulation-v2/charliesWork/temp/pythonGitMain/include/python3.15t/cpython/object.h:497:17: note: previous declaration is here
    497 | PyAPI_FUNC(int) PyUnstable_SetImmortal(PyObject *op);
        |                 ^
  1 error generated.
  [151/329] Compiling C object numpy/_core/_multiarray_umath.cpython-315t-darwin.so.p/meson-generated_nditer_templ.c.o
  [152/329] Compiling Cython source numpy/random/mtrand.pyx
  [153/329] Compiling C++ object numpy/_core/libhighway_qsort.dispatch.h_ASIMD.a.p/src_npysort_highway_qsort.dispatch.cpp.o
  [154/329] Compiling C object numpy/_core/libloops_autovec.dispatch.h_baseline.a.p/meson-generated_loops_autovec.dispatch.c.o
  [155/329] Compiling C object numpy/_core/_multiarray_umath.cpython-315t-darwin.so.p/meson-generated_matmul.c.o
  [156/329] Compiling Cython source numpy/random/_generator.pyx
  [157/329] Compiling C object numpy/_core/_multiarray_umath.cpython-315t-darwin.so.p/meson-generated_einsum_sumprod.c.o
  [158/329] Compiling C object numpy/_core/_multiarray_umath.cpython-315t-darwin.so.p/meson-generated_lowlevel_strided_loops.c.o
  ninja: build stopped: subcommand failed.
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> No available output.
```
my python build is `Python 3.15.0a6+` and I was installing via 
`bin/python3.15t -m pip install -v --no-cache-dir  git+https://github.com/numpy/numpy.git@refs/pull/30826/head `

**Comment by ngoldbaum** [comment]
You'll need to use the actual alpha 6 release tag. Or manually patch the capi-compat header: https://github.com/python/pythoncapi-compat/pull/164#discussion_r2799946915

**Comment by charlieCoalition** [comment]
@ngoldbaum Great! Solid improvement! :D 
`Python 3.15.0a6`
`numpy 2.5.0.dev0+git20260212.41000ac`
```
Model Name: MacBook Pro
Chip: Apple M4 Pro
Total Number of Cores: 14 (10 Performance and 4 Efficiency)
Memory: 48 GB
```
`samply record bin/python3.15t mtmp.py`: https://share.firefox.dev/407nfww    
[mtmp.py](https://github.com/user-attachments/files/25270238/mtmp.py)
```
Python version is free-threaded: True
Inner loops 50, multiprocessing time: 4.94 sec, result sum: 1807379779.548188
Inner loops 50, multithreading  time: 5.74 sec, result sum: 1807379779.548188
```

**Comment by ngoldbaum** [comment]
It looks like all remaining contention is in malloc.

I'm also not sure if allocators on Linux do a better job of this.

Maybe @seberg has some context on the low-level details here?

**Comment by ngoldbaum** [comment]
I wonder if it would help to hook into an alternative allocator that deals with thread contention better, like mimalloc?

**Comment by ngoldbaum** [comment]
It'd be nice to find another benchmark where the malloc contention is a bigger deal at low thread-count so you don't need a beefy machine to see the scaling bottleneck.

**Comment by charlieCoalition** [comment]
I rebuilt python with `--with-mimalloc`:
`Python 3.15.0a6`
`numpy 2.5.0.dev0+git20260212.41000ac`
```
Model Name: MacBook Pro
Chip: Apple M4 Pro
Total Number of Cores: 14 (10 Performance and 4 Efficiency)
Memory: 48 GB
```
`PYTHONMALLOC=mimalloc samply record bin/python3.15t mtmp.py`: https://share.firefox.dev/4bS53OI
[mtmp.py](https://github.com/user-attachments/files/25271442/mtmp.py)
```
WITH_MIMALLOC: 1
Python version is free-threaded: True
Inner loops 50, multiprocessing time: 4.79 sec, result sum: 1807379779.548188
Inner loops 50, multithreading  time: 5.74 sec, result sum: 1807379779.548188
```

**Comment by ngoldbaum** [comment]
Sorry that wasn't what I was saying. I was speculating about using mimalloc in numpy itself. Right now we're directly using the system allocator.

**Comment by kumaraditya303** [comment]
@charlieCoalition  Can you try https://github.com/kumaraditya303/numpy/tree/mimalloc branch and see if that reduces the memory allocation contention?

**Comment by charlieCoalition** [comment]
@kumaraditya303 
```
WITH_MIMALLOC: 1
Python version is free-threaded: True
Inner loops 50, multiprocessing time: 4.55 sec, result sum: 1807379779.548188
zsh: bus error  pythonGitMain/bin/python3.15t
```
I think this could have something to do with the fact that my Python was built with `--with-mimalloc` and got into some conflict with numpy? However Samply did generate the profile for the run: https://share.firefox.dev/4rIz8Vs . It looks promising! Will reinstall Python without `--with-mimalloc` and test

**Comment by kumaraditya303** [comment]
> I think this could have something to do with the fact that my Python was built with --with-mimalloc and got into some conflict with numpy? However Samply did generate the profile for the run: https://share.firefox.dev/4rIz8Vs . It looks promising! Will reinstall Python without --with-mimalloc and test

Oh, I see, it is not a build issue but because the code now uses PyMem_Malloc which requires an active thread state so at runtime shutdown it can crash the interpreter.

**Comment by kumaraditya303** [comment]
@charlieCoalition I pushed a fix for the finalization issue so it should not crash now, please try the latest commit.

**Comment by charlieCoalition** [comment]
@kumaraditya303 Somehow I still get the bus error: 
```
pythonGitMain/bin/python3.15t --version
Python 3.15.0a6
```
```
import numpy as np
np.__version__
'2.5.0.dev0+git20260213.cc8e162'
```
```
WITH_MIMALLOC: 1
Python version is free-threaded: True
Inner loops 50, multiprocessing time: 4.59 sec, result sum: 1807379779.548188
zsh: bus error  pythonGitMain/bin/python3.15t
```
https://share.firefox.dev/3MmQyrR

**Comment by kumaraditya303** [comment]
> Somehow I still get the bus error:

Can you please try https://github.com/python/cpython/pull/144916 and https://github.com/kumaraditya303/numpy/tree/mimalloc? I have switched it now to use raw allocator which doesn't require active thread state so there should no finalization issue.

You would also have make the following change in pythoncapi_compat.h to build against main branch:
```diff
diff --git a/pythoncapi_compat.h b/pythoncapi_compat.h
index e26185c..3447314 100644
--- a/pythoncapi_compat.h
+++ b/pythoncapi_compat.h
@@ -2659,7 +2659,7 @@ PyUnstable_Unicode_GET_CACHED_HASH(PyObject *op)
 }
 #endif
 
-#if 0x030D0000 <= PY_VERSION_HEX && PY_VERSION_HEX < 0x030F00A7 && !defined(PYPY_VERSION)
+#if 0x030D0000 <= PY_VERSION_HEX && PY_VERSION_HEX < 0x030F00A6 && !defined(PYPY_VERSION)
 // Immortal objects were implemented in Python 3.12, however there is no easy API
 // to make objects immortal until 3.14 which has _Py_SetImmortal(). Since
 // immortal objects are primarily needed for free-threading, this API is implemented

```

**Comment by kumaraditya303** [comment]
On linux machine, with https://github.com/python/cpython/pull/144916 + https://github.com/kumaraditya303/numpy/tree/mimalloc:
```console
Inner loops 10, multithreading  time: 8.23 sec, result sum: 717434683.1879177
Inner loops 10, multiprocessing time: 15.82 sec, result sum: 717434683.1879177
```

Profile: https://share.firefox.dev/4awX872

The multi-threaded version is almost twice as fast as multi-processing.

**Comment by seberg** [comment]
> Sorry that wasn't what I was saying. I was speculating about using mimalloc in numpy itself. Right now we're directly using the system allocator.

I guess this is what you asked about a while ago?  I can absolutely see someone being assuming that `malloc/free/realloc` works on arrays allocated by NumPy originally.
That said, I am not too worried. Before we had the custom allocator there was no clear distinction between crazy custom allocated and NumPy allocated arrays, but now there is and that helps.
For free-threading, I think definitely OK (I have little backcompat concern). For non free-threaded builds, I would be up for trying it, but not shocked if we have to revert until a 3.0 release that breaks ABI (that would be gambling that basically nobody is affected, that should hit the mailing list for sure!).

**Comment by charlieCoalition** [comment]
@kumaraditya303 Thank you for the reply! However, on my 
```
Model Name: MacBook Pro
Chip: Apple M4 Pro
Total Number of Cores: 14 (10 Performance and 4 Efficiency)
Memory: 48 GB
```
the following commands
```
git clone https://github.com/python/cpython.git
cd cpython
git fetch origin pull/144916/head:pr-144916 
git checkout pr-144916
./configure --disable-gil  --prefix=/Users/username/Desktop/pythonGitMain
make -j10
make install

pythonGitMain/bin/python3.15t -m pip install git+https://github.com/kumaraditya303/numpy.git@mimalloc
```

led to the following error:
```
In file included from ../numpy/_core/src/umath/scalarmath.c.src:27:
In file included from ../numpy/_core/src/common/binop_override.h:8:
In file included from ../numpy/_core/src/common/get_attr_string.h:5:
In file included from ../numpy/_core/src/common/npy_pycompat.h:5:
../numpy/_core/src/common/pythoncapi-compat/pythoncapi_compat.h:2668:1: error: static declaration of 'PyUnstable_SetImmortal' follows non-static declaration
 2668 | PyUnstable_SetImmortal(PyObject *op)
      | ^
/Users/username/pythonGitMain/include/python3.15t/cpython/object.h:497:17: note: previous declaration is here
  497 | PyAPI_FUNC(int) PyUnstable_SetImmortal(PyObject *op);
      |                 ^
1 error generated.
[149/329] Compiling Cython source /private/var/folders/z5/4406xbpj6ld8jdbn676dh8980000gp/T/pip-req-build-003o0vrq/numpy/random/_common.pyx
[150/329] Compiling C++ object numpy/_core/libhighway_qsort_16bit.dispatch.h_ASIMDHP.a.p/src_npysort_highway_qsort_16bit.dispatch.cpp.o
[151/329] Compiling C object numpy/_core/_multiarray_umath.cpython-315t-darwin.so.p/meson-generated_nditer_templ.c.o
[152/329] Compiling C object numpy/_core/_multiarray_umath.cpython-315t-darwin.so.p/meson-generated_matmul.c.o
[153/329] Compiling C object numpy/_core/libloops_autovec.dispatch.h_baseline.a.p/meson-generated_loops_autovec.dispatch.c.o
[154/329] Compiling Cython source numpy/random/mtrand.pyx
[155/329] Compiling C++ object numpy/_core/libhighway_qsort.dispatch.h_ASIMD.a.p/src_npysort_highway_qsort.dispatch.cpp.o
[156/329] Compiling C object numpy/_core/_multiarray_umath.cpython-315t-darwin.so.p/meson-generated_einsum_sumprod.c.o
[157/329] Compiling Cython source numpy/random/_generator.pyx
[158/329] Compiling C object numpy/_core/_multiarray_umath.cpython-315t-darwin.so.p/meson-generated_lowlevel_strided_loops.c.o
ninja: build stopped: subcommand failed.
[end of output]  
note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> from git+https://github.com/kumaraditya303/numpy.git@mimalloc
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
Maybe it should be another branch?

**Comment by ngoldbaum** [comment]
You're hitting the same issue you hit last week: https://github.com/numpy/numpy/issues/30494#issuecomment-3892461276

**Comment by charlieCoalition** [comment]
@ngoldbaum Thanks! Dumb question: won't pr-144916 auto change it to 3.15.0a6+?

```
git clone https://github.com/python/cpython.git
cd cpython
git checkout tags/v3.15.0a6
git fetch origin pull/144916/head:pr-144916 
git checkout pr-144916
./configure --disable-gil  --prefix=/Users/username/Desktop/pythonGitMain
make -j10
make install

pythonGitMain/bin/python3.15t -m pip install git+https://github.com/kumaraditya303/numpy.git@mimalloc
```

```
pythonGitMain/bin/python3.15t --version
Python 3.15.0a6+
```

```
In file included from ../numpy/_core/src/umath/scalarmath.c.src:27:
In file included from ../numpy/_core/src/common/binop_override.h:8:
In file included from ../numpy/_core/src/common/get_attr_string.h:5:
In file included from ../numpy/_core/src/common/npy_pycompat.h:5:
../numpy/_core/src/common/pythoncapi-compat/pythoncapi_compat.h:2668:1: error: static declaration of 'PyUnstable_SetImmortal' follows non-static declaration
 2668 | PyUnstable_SetImmortal(PyObject *op)
      | ^
/Users/username/pythonGitMain/include/python3.15t/cpython/object.h:497:17: note: previous declaration is here
  497 | PyAPI_FUNC(int) PyUnstable_SetImmortal(PyObject *op);
      |                 ^
1 error generated.
[149/329] Compiling Cython source /private/var/folders/z5/4406xbpj6ld8jdbn676dh8980000gp/T/pip-req-build-003o0vrq/numpy/random/_common.pyx
[150/329] Compiling C++ object numpy/_core/libhighway_qsort_16bit.dispatch.h_ASIMDHP.a.p/src_npysort_highway_qsort_16bit.dispatch.cpp.o
[151/329] Compiling C object numpy/_core/_multiarray_umath.cpython-315t-darwin.so.p/meson-generated_nditer_templ.c.o
[152/329] Compiling C object numpy/_core/_multiarray_umath.cpython-315t-darwin.so.p/meson-generated_matmul.c.o
[153/329] Compiling C object numpy/_core/libloops_autovec.dispatch.h_baseline.a.p/meson-generated_loops_autovec.dispatch.c.o
[154/329] Compiling Cython source numpy/random/mtrand.pyx
[155/329] Compiling C++ object numpy/_core/libhighway_qsort.dispatch.h_ASIMD.a.p/src_npysort_highway_qsort.dispatch.cpp.o
[156/329] Compiling C object numpy/_core/_multiarray_umath.cpython-315t-darwin.so.p/meson-generated_einsum_sumprod.c.o
[157/329] Compiling Cython source numpy/random/_generator.pyx
[158/329] Compiling C object numpy/_core/_multiarray_umath.cpython-315t-darwin.so.p/meson-generated_lowlevel_strided_loops.c.o
ninja: build stopped: subcommand failed.
[end of output]  
note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> from git+https://github.com/kumaraditya303/numpy.git@mimalloc
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by ngoldbaum** [comment]
That's what I meant about hacking the c api compat headers.

The new API didn't quite make it in time for alpha6, so the compat headers aren't quite correct in a way Py_VERSION_HEX can't express. 

Technically the compat header is right, you need alpha7 (or at least a release newer than alpha6). In reality alpha7 hasn't come out yet, so for this limbo month the compat header doesn't
work.

If you change the a7 in the `Py_VERSION_HEX` comparison on this line:

https://github.com/python/pythoncapi-compat/blob/f6121eb60f9fe9ff227fc78f9b39d3bd2a81f434/pythoncapi_compat.h#L2671

to a6 then it will work for you.

The public version of the compat headers can't include that, it would break builds on the real alpha6 release.

**Comment by charlieCoalition** [comment]
@ngoldbaum Thank you! Got it fixed but not sure if I did everything I'm supposed to do. Anyway, on 
```
Model Name: MacBook Pro
Chip: Apple M4 Pro
Total Number of Cores: 14 (10 Performance and 4 Efficiency)
Memory: 48 GB
```
My full installation process is as follows:
```
git clone https://github.com/python/cpython.git
cd cpython                                    
git checkout tags/v3.15.0a6 -b v3.15.0a6-with-pr144916
./configure --disable-gil --prefix=/Users/user/Desktop/pythonGitMain
make -j10
make install
pythonGitMain/bin/python3.15t --version # 3.15.0a6
pythonGitMain/bin/python3.15t -m pip install git+https://github.com/kumaraditya303/numpy.git@mimalloc # success
samply record pythonGitMain/bin/python3.15t mtmp.py
```
Profile: https://share.firefox.dev/4anTnSH
```
WITH_MIMALLOC: 1
Python version is free-threaded: True
Inner loops 50, multiprocessing time: 4.73 sec, result sum: 1807379779.548188
Inner loops 50, multithreading  time: 5.75 sec, result sum: 1807379779.548188
All tasks terminated.
```

[mtmp.py](https://github.com/user-attachments/files/25379077/mtmp.py)

And to @kumaraditya303, thank you for the update and benchmark! Would you mind trying the `mtmp.py` attached in this post? I noticed the one you were using was the very initial script, which already demonstrated less time cost for multithreading after earlier updates. The one attached in this post is simpler and allocates smaller arrays in threads, which gives a harder time for multithreading

**Comment by kumaraditya303** [comment]
> Thank you! Got it fixed but not sure if I did everything I'm supposed to do. Anyway, on

You are not using https://github.com/python/cpython/pull/144916 hence not seeing the improvement in performance.
I have merged that PR upstream now so you can use main branch directly now.

Steps:
```console
git clone https://github.com/python/cpython.git
cd cpython                                    
./configure --disable-gil --prefix=/Users/user/Desktop/pythonGitMain
make -j10
make install
pythonGitMain/bin/python3.15t --version
pythonGitMain/bin/python3.15t -m pip install git+https://github.com/kumaraditya303/numpy.git@mimalloc 
samply record pythonGitMain/bin/python3.15t mtmp.py
```

I have patched my branch of numpy for you so that you don't have to change the compat headers now.

**Comment by charlieCoalition** [comment]
Silly me, thank you! And behold: https://share.firefox.dev/4kKd8Hy
```
WITH_MIMALLOC: 1
Python version is free-threaded: True
Inner loops 50, multiprocessing time: 5.22 sec, result sum: 1807379779.548188
Inner loops 50, multithreading  time: 4.87 sec, result sum: 1807379779.548188
```
To all the wizards in this thread, my genuine and immense appreciation to all of your contributions! You have no idea how great of an impact this update will have on my work!:D

Final question: dare I expect all the relevant changes up including `cpython#144916` and `kumaraditya303/numpy.git@mimalloc` to be released in Python 3.14.4 and NumPy 2.4.3?

**Comment by ngoldbaum** [comment]
Nope, you’ll need to use Python 3.15 alphas and betas and NumPy 2.5 to get the full benefit. A lot of these fixes can’t be backported.

**Comment by kumaraditya303** [comment]
> For free-threading, I think definitely OK (I have little backcompat concern). For non free-threaded builds, I would be up for trying it, but not shocked if we have to revert until a 3.0 release that breaks ABI (that would be gambling that basically nobody is affected, that should hit the mailing list for sure!).


I created https://github.com/numpy/numpy/pull/30846 to use raw allocations APIs under free-threading only. However, I am not sure that it is a safe assumption that numpy arrays or any other memory blocks are allocated directly by system's allocator. For reference the dims cache uses `PyArray_malloc` which is an alias for `PyMem_RawMalloc` so calling `free` on it directly is not safe currently.

**Comment by charlieCoalition** [comment]
> Nope, you’ll need to use Python 3.15 alphas and betas and NumPy 2.5 to get the full benefit. A lot of these fixes can’t be backported.

Thanks! So I presume by Oct this year we can enjoy the benefit officially?:D

**Comment by ngoldbaum** [comment]
Yeah, sorry for the slow timelines on this. We're bound by both CPython and NumPy having official release policies.

That said, I personally am running bleeding-edge branches to test all this stuff and 3.15 support is way way ahead of 3.13 and 3.14 support at the same time as previous years.

**Comment by ngoldbaum** [comment]
Thanks everyone for all the ideas and testing here. Thanks especially to Kumar for doing most of the heavy lifting. This was my favorite NumPy issue in quite a while.

**Comment by ngoldbaum** [comment]
Kumar wrote a blog post about this issue: https://labs.quansight.org/blog/scaling-numpy-on-free-threaded-python
