### ISSUE TITLE
tanh has problems with large complex numbers

### ISSUE THREAD

**Issue by mieswicht** [numpy/numpy#5687]
Hi,

when working with complex impedance data, i encountered an issue and narrowed it down to:

>>> from numpy import *
>>> x=(616.47292227535877+53.814558958179042j)

>>> tanh(x)

Warning (from warnings module):
  File "C:\python\Test\Impedance class reduced.py", line 1
    from numpy import *
RuntimeWarning: overflow encountered in tanh

Warning (from warnings module):
  File "C:\python\Test\Impedance class reduced.py", line 1
    from numpy import *
RuntimeWarning: invalid value encountered in tanh

When actually, it should return (1-0j), see http://tinyurl.com/nm4goq3
Then i tried
>>> sinh(x)/cosh(x)

Warning (from warnings module):
  File "C:\python\Test\Impedance class reduced.py", line 1
    from numpy import *
RuntimeWarning: overflow encountered in cdouble_scalars

Warning (from warnings module):
  File "C:\python\Test\Impedance class reduced.py", line 1
    from numpy import *
RuntimeWarning: invalid value encountered in cdouble_scalars
(nan+nan*j)

However, the solution was to use numpy.divide:

>>> divide(sinh(x),cosh(x))
(1-0j)

This took me quite some time to figure out, so i guess it would be a good idea to include it in the next release (maybe even with with coth?).

Thanks a lot!

**Comment by pv** [comment]
Probably was fixed in gh-5518 some time ago.

**Comment by ewmoore** [comment]
That particular fix is still unreleased, merged mid February 2015.

**Comment by charris** [comment]
Yep, fixed now. Closing this, but I added it to the 1.9.3 milestone just in case we make that release.

**Comment by CarpeCimex** [comment]
With numpy 1.11.2+mkl and Python 3.5.2 I'm seeing this same problem still.  Here's the output from my PyCharm console:

> Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)] on win32
> In[2]: from numpy import *
> x=(616.47292227535877+53.814558958179042j)
> In[3]: tanh(x)
> Out[3]: 
> D:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.2.3\helpers\pydev\pydevconsole.py:1: RuntimeWarning: overflow encountered in tanh
>   '''
> 0j

Needless to say, I see the problem with other large complex numbers too, not just mieswichts' magic number.  :-)

**Comment by njsmith** [comment]
@CarpeCimex: where exactly are you getting numpy from? anaconda?

**Comment by CarpeCimex** [comment]
I got it as a wheel from Christopher Gohlke at http://www.lfd.uci.edu/~gohlke/pythonlibs/ and installed it with pip.

**Comment by mieswicht** [comment]
I still had the problem with numpy 1.9.1 when i checked it right now (never removed my redefinition of tanh), but when I pip upgraded to numpy 1.11.2 , it works fine now.

Python 3.4.2 (v3.4.2:ab2c023a9432, Oct  6 2014, 22:16:31) [MSC v.1600 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> from numpy import *
>>> x=(616.47292227535877+53.814558958179042j)
>>> tanh(x)
(1+0j)

**Comment by CarpeCimex** [comment]
I had to use the "+mkl" version of numpy to work with another package.  
@mieswicht: is yours +mkl?  Also, it looks like your Python is 64 bit AMD (on win 32?), while mine is 32-bit.  That difference might have something to do with it working on yours and not mine.

**Comment by mieswicht** [comment]
No, I dont use +mkl and my machine is 64-bit as is my python.

**Comment by thomasaarholt** [comment]
I'm experiencing `RuntimeWarning: overflow encountered in tanh` when using sympy's `lambdify` to turn a sympy expression into a numpy array. Numpy version 1.14.3.

I'm dealing with relatively large numbers, at least up to 1e16 (this is what survives the overflow warning).
Here is a [traceback ](https://gist.github.com/thomasaarholt/f89fc41a08ac7caa2b8a53c4649b621e)of the warning, for anyone interested.

**Comment by moboh** [comment]
Hi, I am in np.version 1.19.2 and this is still a thing.

**Comment by charris** [comment]
What platform?

**Comment by moboh** [comment]
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

On 3. May 2021, at 16:46, Charles Harris ***@***.******@***.***>> wrote:



What platform?

**Comment by ngodber** [comment]
Hi,

This bug is very much still in the wild - reproducible on win x64 in python 3.9.x and np 1.20.x

Related issue:
https://github.com/simpeg/simpeg/issues/1042

Cheers,
N

**Comment by richinex** [comment]
Bug still there - I'm on a win x64 with python 3.9.x and np 1.21.x. However, with the same code I don't experience the warnings on my linux. I dunno.

**Comment by pililac** [comment]
I'm having the same problem when using [impedance.py](https://github.com/ECSHackWeek/impedance.py). I'm using Python 3.10.6, Numpy 1.23.3 on a Windows PC.

```
RuntimeWarning: overflow encountered in tanh
  Z = Z0/(np.sqrt(1j*omega*tau)*np.tanh(np.sqrt(1j*omega*tau)))
```

**Comment by charris** [comment]
@pililac Where did you get NumPy?

**Comment by seberg** [comment]
I think MSVC has no complex support (that is basically not implementing C99 completely).  I am not quite certain about newer versions.
Also, I think it may have complex support in C++ mode, so that might be a solution?

Right now, I expect we are using fallback versions on MSVC and those do not have branches to deal well with large values.

**Comment by pililac** [comment]
> @pililac Where did you get NumPy?

I installed it via conda using miniforge. Here is a partial view of `conda list`:

```
(data_analysis) C:\Users\user_01>conda list
# packages in environment at C:\other_software\miniforge3\envs\data_analysis:
#
# Name                    Version                   Build  Channel
...
numpy                     1.23.3          py310h4a8f9c9_0    conda-forge
...
```

**Comment by seberg** [comment]
Ah, correction.  MSVC has it, and we should be using it. Unless our `HAVE_CTANH` macro is not working properly on windows, we should be using the microsoft version.

Of course it is plausible that the microsoft shipped `ctanh` has problems with large numbers itself.

@hoodmane I am worried that in an attempt to use the correct signature during function discovery in gh-21154 we may have broken discovery for complex types (which require passing a strange type, at least on MSVC).
In that case, this would effectively be a regression in NumPy 1.23.x.

**Comment by seberg** [comment]
Hmmm, looking at what is generated (sorry not on windows right now).  It may be we are probing complex functions without any signature (I suppose the wasm code is happy to use the fallbacks), using for example:
```
int catanh (void);
#ifdef _MSC_VER
#pragma function(catanh)
#endif
int main (void) {
  catanh();
  return 0;
}
```
Now, plugging that into godbolt: https://godbolt.org/z/WGeYxcbn7 it gives an error.

MSVC seems to be OK with this for some very simple functions (like `abs`), which is what the pragma makes work.  Unless someone knows windows right away, we really need to check up on windows/MSVC here, whether the detection is doing the right thing.

The detection here is going via: https://github.com/numpy/numpy/blob/main/numpy/distutils/command/config.py#L316 or `check_funcs_once` below (if that is successful, which I am doubting).

**Comment by seberg** [comment]
Sorry, I am silly.  The godbolt code had the includes in there, which is wrong.  The way it works is trying to link, not trying to compile...

**Comment by seberg** [comment]
OK, if you start something have to look it through I guess.  After almost setting up windows, I realized that godbolt does the trick:
https://godbolt.org/z/Trz4sxhn3

Which shows that we *are* using the MSVC version when the result is 0.  The version that NumPy would be using as a fallback *does* return `1+0j` for the example.

I am not sure if the right solution is to just consider this an MSVC bug (or just deficiency) or whether we should blacklist MSVC for `ctanh` and use our own version.

**Comment by charris** [comment]
@seberg We should establish if the conda version is using MKL, which may have its own libraries. Once we determine which library is failing we should file a bug upstream and use the fallback version, which should be OK since we don't have extended precision on windows.

**Comment by seberg** [comment]
@charris I am not aware that MKL can replace math functions at run-time for scalars values (or even provides those)?  (Unless this was patched by Intel, but those patched versions seem to not really be used much anymore.)

We do have SIMD versions for `tanh` actually (roughly based on the SVML algorithm).  But that version does seem to have the correct checks for large inputs.

Sounds like we should just blocklist.  I agree that it should be filed as a bug upstream, I will try to do it.  Last time, I didn't because they are very restrictive about requiring and making things public, but...

**Comment by seberg** [comment]
Hmmm, I reported an issue, not sure if in the right place, since the C++ version `std::tanh` actually does the right thing in MSCV, it is just the C99 version that is wrong:  https://godbolt.org/z/aoxEqnEnj

**Comment by seberg** [comment]
Ah, interesting tidbit maybe.  And something that I guess the previous comments also point to:  The issue only reproduces with x86 mode on godbolt (I got lucky to pick that first...) and not x64.

**Comment by abcde2342** [comment]
I think this issue can be closed. The result is right now. By the way, here is my patch:

```
    q = cmath.exp(-2 * z)
    patched = 1 - 2 * q + 2 * q * q
```

**Comment by seberg** [comment]
Thanks for the note, I think you are right and this is fixed in the minimum MSVC version we support now.
