### ISSUE TITLE
many boundary issues detected in clang 3.6 with -fsanitize=undefined for numpy 1.9.2

### ISSUE THREAD

**Issue by howarthjw** [numpy/numpy#5736]
Building numpy 1.9.2 with the clang 3.6 compilers and the -fsanitize=undefined triggered many runtime error messages during the unit tests for numpy. A sampling of these detected on x86_64-apple-darwin14 are...

numpy/core/src/multiarray/iterators.c:333:5: runtime error: index -1 out of bounds for type 'npy_intp [32]'
numpy/core/src/multiarray/iterators.c:1413:9: runtime error: index -1 out of bounds for type 'npy_intp [32]'
numpy/core/src/multiarray/common.h:161:35: runtime error: load of misaligned address 0x7fb8ca9519f2 for type 'unsigned int', which requires 4 byte alignment
numpy/core/src/multiarray/datetime.c:991:13: runtime error: index 26 out of bounds for type 'NPY_DATETIMEUNIT [16][4]'
numpy/core/src/multiarray/datetime.c:992:16: runtime error: index 27 out of bounds for type 'NPY_DATETIMEUNIT [16][4]'
(/sw/src/fink.build/root-numpy-py27-1.9.2-3/sw/lib/python2.7/site-packages/numpy/core/multiarray.so+0x4e15ea): runtime error: value 34440 is outside the range of representable values of type 'short'
(/sw/src/fink.build/root-numpy-py27-1.9.2-3/sw/lib/python2.7/site-packages/numpy/core/multiarray.so+0x4e15ea): runtime error: value 130 is outside the range of representable values of type 'signed char'
.(/sw/src/fink.build/root-numpy-py27-1.9.2-3/sw/lib/python2.7/site-packages/numpy/core/multiarray.so+0x4e15ea): runtime error: value 325 is outside the range of representable values of type 'unsigned char'
.numpy/core/src/multiarray/arraytypes.c.src:536:5: runtime error: load of misaligned address 0x7fb8cac0730c for type 'PyObject *' (aka 'struct _object *'), which requires 8 byte alignment
Knumpy/core/src/umath/loops.c.src:1490:40: runtime error: division by zero
(/sw/src/fink.build/root-numpy-py27-1.9.2-3/sw/lib/python2.7/site-packages/numpy/core/multiarray.so+0x4e15ea): runtime error: value inf is outside the range of representable values of type 'long'
(/sw/src/fink.build/root-numpy-py27-1.9.2-3/sw/lib/python2.7/site-packages/numpy/core/multiarray.so+0x4e15ea): runtime error: value nan is outside the range of representable values of type 'long'
(/sw/src/fink.build/root-numpy-py27-1.9.2-3/sw/lib/python2.7/site-packages/numpy/core/multiarray.so+0x4e15ea): runtime error: value -inf is outside the range of representable values of type 'long'

...for a total of 16696 runtime errors detected by UBSan as described in...

https://docs.python.org/devguide/clang.html

**Comment by charris** [comment]
One suspects that most of these don't matter, for instance `multiarray.so+0x4e15ea` seems to account for many repeat warnings. Probably more care needs to be exercised in setting up the checks in order to get anything useful. 16696 errors is not useful, especially if numpy doesn't crash an burn in every application.

**Comment by pv** [comment]
The messages about misalignment, division by zero, and out-of-range assignments can probably all be disregarded as a first approximation.

**Comment by pv** [comment]
@howarthjw: please go ahead and upload the full log to http://gist.github.com or somewhere, and add a link to it here.

**Comment by howarthjw** [comment]
The log is posted at https://gist.github.com/howarthjw/f5163c64b7d0b11ce202

**Comment by howarthjw** [comment]
The stock clang 3.6 build also produces potentially useful warnings like...

In file included from numpy/core/src/umath/umathmodule.c:40:

numpy/core/src/umath/funcs.inc.src:464:9: warning: absolute value function
'fabs' given an argument of type 'npy_longdouble' (aka 'long double') but
has parameter of type 'double' which may cause truncation of value
[-Wabsolute-value]

    if (fabs(x->real) > 1e-3 || fabs(x->imag) > 1e-3) {

        ^

I've uploaded a full build log for numpy 1.9.2 on x86_64-apple-darwin14
with clang 3.6 at https://gist.github.com/howarthjw/878b8c8794fe5cc54e07

**Comment by howarthjw** [comment]
Clang 3.6 produces warnings of the form...

warning: absolute value function 'fabs' given an argument of type
'npy_longdouble' (aka 'long double') but has parameter of type 'double'
which may cause truncation of value [-Wabsolute-value]


unless the following change is made,

diff -uNr numpy-1.9.2.orig/numpy/core/src/umath/funcs.inc.src
numpy-1.9.2/numpy/core/src/umath/funcs.inc.src
--- numpy-1.9.2.orig/numpy/core/src/umath/funcs.inc.src 2015-02-01
11:38:21.000000000 -0500
+++ numpy-1.9.2/numpy/core/src/umath/funcs.inc.src 2015-03-29
17:15:57.000000000 -0400
@@ -461,7 +461,7 @@
      * return nc_neg(nc_prodi(nc_log(nc_sum(nc_prod(nc_i,x),
      * nc_sqrt(nc_diff(nc_1,nc_prod(x,x)))))));
      */
-    if (fabs(x->real) > 1e-3 || fabs(x->imag) > 1e-3) {
+    if (fabsl(x->real) > 1e-3 || fabs(x->imag) > 1e-3) {
         @ctype@ a, *pa=&a;
         nc_prod@c@(x, x, r);
         nc_diff@c@(&nc_1@c@, r, r);
@@ -504,7 +504,7 @@
     /*
      * return nc_log(nc_sum(nc_sqrt(nc_sum(nc_1,nc_prod(x,x))),x));
      */
-    if (fabs(x->real) > 1e-3 || fabs(x->imag) > 1e-3) {
+    if (fabsl(x->real) > 1e-3 || fabs(x->imag) > 1e-3) {
         nc_prod@c@(x, x, r);
         nc_sum@c@(&nc_1@c@, r, r);
         nc_sqrt@c@(r, r);
@@ -542,7 +542,7 @@
     /*
      * return
nc_prod(nc_i2,nc_log(nc_quot(nc_sum(nc_i,x),nc_diff(nc_i,x))));
      */
-    if (fabs(x->real) > 1e-3 || fabs(x->imag) > 1e-3) {
+    if (fabsl(x->real) > 1e-3 || fabs(x->imag) > 1e-3) {
         @ctype@ a, *pa=&a;
         nc_diff@c@(&nc_i@c@, x, pa);
         nc_sum@c@(&nc_i@c@, x, r);
@@ -581,7 +581,7 @@
     /*
      * return
nc_prod(nc_half,nc_log(nc_quot(nc_sum(nc_1,x),nc_diff(nc_1,x))));
      */
-    if (fabs(x->real) > 1e-3 || fabs(x->imag) > 1e-3) {
+    if (fabsl(x->real) > 1e-3 || fabs(x->imag) > 1e-3) {
         @ctype@ a, *pa=&a;
         nc_diff@c@(&nc_1@c@, x, r);
         nc_sum@c@(&nc_1@c@, x, pa);

**Comment by juliantaylor** [comment]
doesn't mac have type generic math?

also you should use git master, I already went through and fixed some ubsan issues (based on gcc's version) though there are still some remaining, but nothing really important

**Comment by howarthjw** [comment]
Regarding the warnings to use fabs(), I see that other projects are either explicitly making the change...

https://bugs.webkit.org/show_bug.cgi?id=130286

or using std::abs() in the case of c++ code (which doesn't trigger the warning)...

https://bugzilla.mozilla.org/show_bug.cgi?id=1073716

**Comment by njsmith** [comment]
I don't think anyone would object if you submitted a patch to use fabs
instead of abs when appropriate. The problem isn't so much that we don't
care about fixing things as that ATM from this report I have no idea what
actually needs fixing, if anything -- it isn't very actionable. This is the
first time abs has even been mentioned in this thread AFAICT.

**Comment by jaimefrio** [comment]
On Thu, Apr 16, 2015 at 8:52 AM, Nathaniel J. Smith <
notifications@github.com> wrote:

> I don't think anyone would object if you submitted a patch to use fabs
> instead of abs when appropriate. The problem isn't so much that we don't
> care about fixing things as that ATM from this report I have no idea what
> actually needs fixing, if anything -- it isn't very actionable. This is the
> first time abs has even been mentioned in this thread AFAICT.


As Julian pointed earlier in this thread, the fabs vs fabsl thing is
already fixed in master, at least for some of the occurrences. So for this
report to be helpful it would have to be re-run on master. And then yes,
PRs to fix compiler warnings are more than welcome!

Jaime

-- 
(\__/)
( O.o)
( > <) Este es Conejo. Copia a Conejo en tu firma y ayúdale en sus planes
de dominación mundial.

**Comment by juliantaylor** [comment]
abs is not fabs in C, abs is not for floating point and not covered by the C type generic math.
but I don't mind making it explicit, its unnecessary from a correctness standpoint but I'm all for reducing noise in dynamic analysis where it is reasonable to do so.

**Comment by seberg** [comment]
This may still have some valid points (dynamic code analyis of old numpy version), but the analysis would have to be rerun on master to be very valuable as pointed out before. So I will close this.
