### ISSUE TITLE
Precision loss when casting 19-digit integer to float

### ISSUE THREAD

**Issue by albertvillanova** [numpy/numpy#9006]
When I cast an array containing 19-digit integers to float (even to float128), the precision of the last 2 digits is lost:

```
In [5]: a = np.array([1493026669447931676], dtype=np.float128)

In [6]: np.int64(a[0])
Out[6]: 1493026669447931648
```

Nevertheless, this is not the case if I first cast the array to int64:
```
In [7]: a = np.array([1493026669447931676, 1493026669447931679], dtype=np.int64)

In [8]: b = a.astype(np.float128)

In [9]: np.int64(b[0])
Out[9]: 1493026669447931676
```
What is this precision loss due to? Why this inconsistency between the two different approaches?

I am using Numpy 1.11.3 and Pyhton 3.4.

**Comment by eric-wieser** [comment]
This looks like #8903 to me

**Comment by eric-wieser** [comment]
That is, I think this is already fixed on master. Unfortunately, I'm not on a platform with `float128`, so cannot check this.

Are you able to install numpy from master and verify this with `runtests.py -i`, which would open an ipython shell you can try this in?

**Comment by eric-wieser** [comment]
@charris: Is #8903 worthy of a backport?

**Comment by albertvillanova** [comment]
@eric-wieser I have tried the dev version (1.13.0.dev0+bca7922) and the bug is not fixed:
```
>>> import numpy as np
>>> np.__version__
'1.13.0.dev0+bca7922'
>>> a = np.array([1493026669447931676, 1493026669447931679], dtype=np.float128)
>>> np.int64(a[0])
1493026669447931648
```

**Comment by eric-wieser** [comment]
Darn, thanks for testing. I still reckon that the cause is a cast to `float` somewhere, but I guess we make that mistake somewhere else too

**Comment by eric-wieser** [comment]
Actually, it's in the same place - under the guise of a function that is supposed to convert strings to long doubles - at `arraytypes.c.src@string_to_long_double`, there is a call to `MyPyFloat_AsDouble`, which essentially calls `float`.

The fix is simple - before `LONGDOUBLE_setitem` tries to decode a string, it should check if it has a python integer, and convert that.

To handle python `long`s, I think the only valid approach is to convert the integer to a string, and then convert that string to a longdouble in the same way we could handle strings - `long` objects are otherwise opaque.

**Comment by eric-wieser** [comment]
A related thing to test - is `np.longdouble("1.234...")` always the same as `np.longdouble(decimal.Decimal("1.234..."))`?

**Comment by charris** [comment]
@eric-wieser Backports are mostly for regressions. Some bug fixes get in, but fixes for longstanding bugs like this that folks have managed to live with are more in the normal course of release to release improvements. Which is to say, I don't think #8903 is worth a backport.

There is some judgement involved. If a new version is taking a very long time to come out, then the current version becomes a bit like a long term release. But as long as we manage to get out 2-3 new releases a year the effort is better spent moving forward.

**Comment by eric-wieser** [comment]
I think this was fixed in 9d157f3d931bed594dcf817a8bfff94bcbd1a592

**Comment by seberg** [comment]
Yes, just checked. The initially reported examples all give the correct answer on 1.16.
