### ISSUE TITLE
numpy genfromtxt does not work with converters returning strings

### ISSUE THREAD

**Issue by oivulf** [numpy/numpy#9644]
When calling genfromtxt as e.g. in:
data=np.genfromtxt('all.txt',dtype=None,names=True,missing_values='NA',converters={6:lambda s: 'ex'})
the converted column is empty string.
These also does not work as I expected, i.e. returning strings instead of bytes:

data=np.genfromtxt('all.txt',dtype=(int,float,float,float,float,float,str),names=True,missing_values='NA')

data=np.genfromtxt('all.txt',dtype=None,names=True,missing_values='NA',converters={6:lambda s: s.decode('UTF8')})

[all.txt](https://github.com/numpy/numpy/files/1272272/all.txt)

**Comment by juliantaylor** [comment]
this probably causes it, this addition for usecols basically breaks string converters with names=True
https://github.com/numpy/numpy/blob/11593aa176d491beb0cc5ffcc393956a5435a2bf/numpy/lib/npyio.py#L1770

the byte based interface is fixed in https://github.com/numpy/numpy/pull/4208

**Comment by oivulf** [comment]
Uhm,
even changing 
names=True 
to
names='a,b,c,d,e,f,g'
does not work.
Changing dtype to str yields all empty strings.
My numpy version is 1.13.1
data=np.genfromtxt('all.txt',dtype='str,str,str,str,str,str,str',names='a,b,
     ...: c,d,e,f,g',missing_values='NA',converters={6:lambda s: 'ex'})
array([('', '', '', '', '', '', ''), ('', '', '', '', '', '', ''),
       ('', '', '', '', '', '', ''), ('', '', '', '', '', '', ''),

**Comment by pmgast** [comment]
I would like to note that this is still an issue in version 1.17.4 and 1.22.0rc1
```python
>>> np.genfromtxt('test.txt',dtype=str,skip_header=1,delimiter=';')
array([['11', 'Server', 'Berlin'],
       ['1', 'Client', 'Stralsund']], dtype='<U9')
```
works. but
```python
>>> np.genfromtxt('test.txt',dtype=np.dtype('U8'),names=True,delimiter=';',encoding=None)
array([('', '', ''), ('', '', '')],
      dtype={'names':['z1','z2','z3'], 'formats':['<U','<U','<U'], 'offsets':[0,0,0], 'itemsize':3})
```
produces garbage. I know one can set each column dtype explicitly but this behavior is hard to understand.
